'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class EN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SD_Download_Manager.EN", GetType(EN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property AboutToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("AboutToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property AboutToolStripMenuItem1() As String
            Get
                Return ResourceManager.GetString("AboutToolStripMenuItem1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property ADButton1() As String
            Get
                Return ResourceManager.GetString("ADButton1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property ADButton2() As String
            Get
                Return ResourceManager.GetString("ADButton2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Download later.
        '''</summary>
        Friend Shared ReadOnly Property ADchdlnow() As String
            Get
                Return ResourceManager.GetString("ADchdlnow", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Use deafult path.
        '''</summary>
        Friend Shared ReadOnly Property ADchdpath() As String
            Get
                Return ResourceManager.GetString("ADchdpath", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Use authorization.
        '''</summary>
        Friend Shared ReadOnly Property ADCheckBox1() As String
            Get
                Return ResourceManager.GetString("ADCheckBox1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Add link.
        '''</summary>
        Friend Shared ReadOnly Property Addlink() As String
            Get
                Return ResourceManager.GetString("Addlink", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Add URL.
        '''</summary>
        Friend Shared ReadOnly Property AddLinkToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("AddLinkToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Address :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel1() As String
            Get
                Return ResourceManager.GetString("ADLabel1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Username :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel2() As String
            Get
                Return ResourceManager.GetString("ADLabel2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Password :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel3() As String
            Get
                Return ResourceManager.GetString("ADLabel3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Description :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel6() As String
            Get
                Return ResourceManager.GetString("ADLabel6", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to File name :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel7() As String
            Get
                Return ResourceManager.GetString("ADLabel7", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Description .
        '''</summary>
        Friend Shared ReadOnly Property ADlbldescription() As String
            Get
                Return ResourceManager.GetString("ADlbldescription", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Arrange files.
        '''</summary>
        Friend Shared ReadOnly Property ArrangeFilesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ArrangeFilesToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to By File Name.
        '''</summary>
        Friend Shared ReadOnly Property ByFileNameToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByFileNameToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to By ID.
        '''</summary>
        Friend Shared ReadOnly Property ByIDToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByIDToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to By Last Try Date.
        '''</summary>
        Friend Shared ReadOnly Property ByLastTryDateToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByLastTryDateToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to By Time left.
        '''</summary>
        Friend Shared ReadOnly Property ByLeftTimeToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByLeftTimeToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to By Size.
        '''</summary>
        Friend Shared ReadOnly Property BySizeToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("BySizeToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to By Status.
        '''</summary>
        Friend Shared ReadOnly Property ByStatusToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByStatusToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to By Speed.
        '''</summary>
        Friend Shared ReadOnly Property ByToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Use system proxy.
        '''</summary>
        Friend Shared ReadOnly Property checkuseproxy() As String
            Get
                Return ResourceManager.GetString("checkuseproxy", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Last try date.
        '''</summary>
        Friend Shared ReadOnly Property CLdate() As String
            Get
                Return ResourceManager.GetString("CLdate", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property CLDescription() As String
            Get
                Return ResourceManager.GetString("CLDescription", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Link.
        '''</summary>
        Friend Shared ReadOnly Property CLink() As String
            Get
                Return ResourceManager.GetString("CLink", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property CLname() As String
            Get
                Return ResourceManager.GetString("CLname", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property CLnomber() As String
            Get
                Return ResourceManager.GetString("CLnomber", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property CLpassword() As String
            Get
                Return ResourceManager.GetString("CLpassword", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Size.
        '''</summary>
        Friend Shared ReadOnly Property CLsize() As String
            Get
                Return ResourceManager.GetString("CLsize", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Speed.
        '''</summary>
        Friend Shared ReadOnly Property CLspeed() As String
            Get
                Return ResourceManager.GetString("CLspeed", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property CLstatus() As String
            Get
                Return ResourceManager.GetString("CLstatus", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Time left .
        '''</summary>
        Friend Shared ReadOnly Property CLtime() As String
            Get
                Return ResourceManager.GetString("CLtime", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to User name.
        '''</summary>
        Friend Shared ReadOnly Property CLusername() As String
            Get
                Return ResourceManager.GetString("CLusername", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property DELbtnno() As String
            Get
                Return ResourceManager.GetString("DELbtnno", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property DELbtnyes() As String
            Get
                Return ResourceManager.GetString("DELbtnyes", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Don&apos;t show this dialog again.
        '''</summary>
        Friend Shared ReadOnly Property DELcheckdontshow() As String
            Get
                Return ResourceManager.GetString("DELcheckdontshow", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Delete completed.
        '''</summary>
        Friend Shared ReadOnly Property DeleteAllcompletedToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("DeleteAllcompletedToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Do you agree to delete this file/s ?.
        '''</summary>
        Friend Shared ReadOnly Property DELLabel1() As String
            Get
                Return ResourceManager.GetString("DELLabel1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Delete request.
        '''</summary>
        Friend Shared ReadOnly Property DELmsgdelete() As String
            Get
                Return ResourceManager.GetString("DELmsgdelete", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Pause.
        '''</summary>
        Friend Shared ReadOnly Property DLbtnpause() As String
            Get
                Return ResourceManager.GetString("DLbtnpause", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Resume.
        '''</summary>
        Friend Shared ReadOnly Property DLbtnresume() As String
            Get
                Return ResourceManager.GetString("DLbtnresume", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property DLbtnstop() As String
            Get
                Return ResourceManager.GetString("DLbtnstop", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;&lt; Hide details.
        '''</summary>
        Friend Shared ReadOnly Property DLclosetext() As String
            Get
                Return ResourceManager.GetString("DLclosetext", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Exit SD download manager when done.
        '''</summary>
        Friend Shared ReadOnly Property DLexitchek() As String
            Get
                Return ResourceManager.GetString("DLexitchek", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Force processes to terminate.
        '''</summary>
        Friend Shared ReadOnly Property DLforceturnoffcheck() As String
            Get
                Return ResourceManager.GetString("DLforceturnoffcheck", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Downloaded.
        '''</summary>
        Friend Shared ReadOnly Property DLl1() As String
            Get
                Return ResourceManager.GetString("DLl1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property DLl2() As String
            Get
                Return ResourceManager.GetString("DLl2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to File Size.
        '''</summary>
        Friend Shared ReadOnly Property DLl3() As String
            Get
                Return ResourceManager.GetString("DLl3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Transfer rate.
        '''</summary>
        Friend Shared ReadOnly Property DLl4() As String
            Get
                Return ResourceManager.GetString("DLl4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Time left.
        '''</summary>
        Friend Shared ReadOnly Property DLl5() As String
            Get
                Return ResourceManager.GetString("DLl5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to File type.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel10() As String
            Get
                Return ResourceManager.GetString("DLLabel10", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Resume capability.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel14() As String
            Get
                Return ResourceManager.GetString("DLLabel14", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Elapsed time.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel15() As String
            Get
                Return ResourceManager.GetString("DLLabel15", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Total segments.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel16() As String
            Get
                Return ResourceManager.GetString("DLLabel16", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Current segment.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel17() As String
            Get
                Return ResourceManager.GetString("DLLabel17", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Save to.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel7() As String
            Get
                Return ResourceManager.GetString("DLLabel7", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to These setting are unavailable when &quot;Show download coplated dialog&quot; is turned on.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel9() As String
            Get
                Return ResourceManager.GetString("DLLabel9", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Downloaded.
        '''</summary>
        Friend Shared ReadOnly Property DLList1Downloaded() As String
            Get
                Return ResourceManager.GetString("DLList1Downloaded", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property DLList1ID() As String
            Get
                Return ResourceManager.GetString("DLList1ID", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property DLList1sts() As String
            Get
                Return ResourceManager.GetString("DLList1sts", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Show details &gt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property DLopentext() As String
            Get
                Return ResourceManager.GetString("DLopentext", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Option on completion.
        '''</summary>
        Friend Shared ReadOnly Property DLoptiontab() As String
            Get
                Return ResourceManager.GetString("DLoptiontab", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Turn off computer when done.
        '''</summary>
        Friend Shared ReadOnly Property DLpcturnoffchek() As String
            Get
                Return ResourceManager.GetString("DLpcturnoffchek", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Show download completed dialog.
        '''</summary>
        Friend Shared ReadOnly Property DLshowdialogchk() As String
            Get
                Return ResourceManager.GetString("DLshowdialogchk", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Download status.
        '''</summary>
        Friend Shared ReadOnly Property DLstatustab() As String
            Get
                Return ResourceManager.GetString("DLstatustab", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property ExitToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend Shared ReadOnly Property FDbtnclose() As String
            Get
                Return ResourceManager.GetString("FDbtnclose", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Send.
        '''</summary>
        Friend Shared ReadOnly Property FDbtnersal() As String
            Get
                Return ResourceManager.GetString("FDbtnersal", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Weblog.
        '''</summary>
        Friend Shared ReadOnly Property FDbtnweb() As String
            Get
                Return ResourceManager.GetString("FDbtnweb", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Please enter your name and email address.
        '''</summary>
        Friend Shared ReadOnly Property FDGroupBox1() As String
            Get
                Return ResourceManager.GetString("FDGroupBox1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Please write comments or suggestions or bugs in the software and click on the &quot;Send&quot; button.
        '''</summary>
        Friend Shared ReadOnly Property FDGroupBox2() As String
            Get
                Return ResourceManager.GetString("FDGroupBox2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Attach :.
        '''</summary>
        Friend Shared ReadOnly Property FDlblattach() As String
            Get
                Return ResourceManager.GetString("FDlblattach", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to E-Mail .
        '''</summary>
        Friend Shared ReadOnly Property FDlblmail() As String
            Get
                Return ResourceManager.GetString("FDlblmail", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Name .
        '''</summary>
        Friend Shared ReadOnly Property FDlblname() As String
            Get
                Return ResourceManager.GetString("FDlblname", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Subject .
        '''</summary>
        Friend Shared ReadOnly Property FDlblsubject() As String
            Get
                Return ResourceManager.GetString("FDlblsubject", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Feedback.
        '''</summary>
        Friend Shared ReadOnly Property FeedbackToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("FeedbackToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to File.
        '''</summary>
        Friend Shared ReadOnly Property FilesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("FilesToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend Shared ReadOnly Property HelpToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("HelpToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Icons.
        '''</summary>
        Friend Shared ReadOnly Property IconsToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("IconsToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Feedback.
        '''</summary>
        Friend Shared ReadOnly Property Label10() As String
            Get
                Return ResourceManager.GetString("Label10", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Drop Target.
        '''</summary>
        Friend Shared ReadOnly Property Label11() As String
            Get
                Return ResourceManager.GetString("Label11", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Add link.
        '''</summary>
        Friend Shared ReadOnly Property Label2() As String
            Get
                Return ResourceManager.GetString("Label2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Resume.
        '''</summary>
        Friend Shared ReadOnly Property Label3() As String
            Get
                Return ResourceManager.GetString("Label3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Stop.
        '''</summary>
        Friend Shared ReadOnly Property Label4() As String
            Get
                Return ResourceManager.GetString("Label4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Stop All.
        '''</summary>
        Friend Shared ReadOnly Property Label5() As String
            Get
                Return ResourceManager.GetString("Label5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Scheduler.
        '''</summary>
        Friend Shared ReadOnly Property Label6() As String
            Get
                Return ResourceManager.GetString("Label6", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property Label7() As String
            Get
                Return ResourceManager.GetString("Label7", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Delete completed.
        '''</summary>
        Friend Shared ReadOnly Property Label8() As String
            Get
                Return ResourceManager.GetString("Label8", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend Shared ReadOnly Property Label9() As String
            Get
                Return ResourceManager.GetString("Label9", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property LanguageToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("LanguageToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Save to.
        '''</summary>
        Friend Shared ReadOnly Property Llocation() As String
            Get
                Return ResourceManager.GetString("Llocation", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Network is not available , Please check your internet connection and then try again.
        '''</summary>
        Friend Shared ReadOnly Property NoInternet() As String
            Get
                Return ResourceManager.GetString("NoInternet", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Normal.
        '''</summary>
        Friend Shared ReadOnly Property NormalToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("NormalToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property OPbtncancel() As String
            Get
                Return ResourceManager.GetString("OPbtncancel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Check for new version.
        '''</summary>
        Friend Shared ReadOnly Property OPbtncheckfornewversion() As String
            Get
                Return ResourceManager.GetString("OPbtncheckfornewversion", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnedit() As String
            Get
                Return ResourceManager.GetString("OPbtnedit", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnnew() As String
            Get
                Return ResourceManager.GetString("OPbtnnew", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnok() As String
            Get
                Return ResourceManager.GetString("OPbtnok", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Remove.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnremove() As String
            Get
                Return ResourceManager.GetString("OPbtnremove", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend Shared ReadOnly Property opButton1() As String
            Get
                Return ResourceManager.GetString("opButton1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Default.
        '''</summary>
        Friend Shared ReadOnly Property opButton2() As String
            Get
                Return ResourceManager.GetString("opButton2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Remove.
        '''</summary>
        Friend Shared ReadOnly Property opButton3() As String
            Get
                Return ResourceManager.GetString("opButton3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Select font.
        '''</summary>
        Friend Shared ReadOnly Property OPButton4() As String
            Get
                Return ResourceManager.GetString("OPButton4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Select texts color.
        '''</summary>
        Friend Shared ReadOnly Property OPButton5() As String
            Get
                Return ResourceManager.GetString("OPButton5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Select forms background color.
        '''</summary>
        Friend Shared ReadOnly Property OPButton6() As String
            Get
                Return ResourceManager.GetString("OPButton6", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Restore default.
        '''</summary>
        Friend Shared ReadOnly Property OPButton7() As String
            Get
                Return ResourceManager.GetString("OPButton7", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Check for update automaticaly.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckautoupdate() As String
            Get
                Return ResourceManager.GetString("OPcheckautoupdate", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Download failed.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckcancelled() As String
            Get
                Return ResourceManager.GetString("OPcheckcancelled", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Download completed.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckcompleted() As String
            Get
                Return ResourceManager.GetString("OPcheckcompleted", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Use default path for downloads.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckdefaultpath() As String
            Get
                Return ResourceManager.GetString("OPcheckdefaultpath", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Dont show delete dialog when deleting files from list.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckdontshoedelete() As String
            Get
                Return ResourceManager.GetString("OPcheckdontshoedelete", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Grab download link from clipboard.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckgrabfromclipboard() As String
            Get
                Return ResourceManager.GetString("OPcheckgrabfromclipboard", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Use old icons.
        '''</summary>
        Friend Shared ReadOnly Property OPCheckOldIcons() As String
            Get
                Return ResourceManager.GetString("OPCheckOldIcons", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Show desktop notification when download Completed.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckshownotification() As String
            Get
                Return ResourceManager.GetString("OPcheckshownotification", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Start SD Download Manager on windows startup.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckstartup() As String
            Get
                Return ResourceManager.GetString("OPcheckstartup", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Automatically start downloading just the following file types.
        '''</summary>
        Friend Shared ReadOnly Property opcheckusefiletype() As String
            Get
                Return ResourceManager.GetString("opcheckusefiletype", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property OPCpass() As String
            Get
                Return ResourceManager.GetString("OPCpass", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Site/Path.
        '''</summary>
        Friend Shared ReadOnly Property OPCsite() As String
            Get
                Return ResourceManager.GetString("OPCsite", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Friend Shared ReadOnly Property OPCuser() As String
            Get
                Return ResourceManager.GetString("OPCuser", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Open with.
        '''</summary>
        Friend Shared ReadOnly Property OPEbtnopenwith() As String
            Get
                Return ResourceManager.GetString("OPEbtnopenwith", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend Shared ReadOnly Property OPEButton1() As String
            Get
                Return ResourceManager.GetString("OPEButton1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Open folder.
        '''</summary>
        Friend Shared ReadOnly Property OPEButton3() As String
            Get
                Return ResourceManager.GetString("OPEButton3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend Shared ReadOnly Property OPEButton4() As String
            Get
                Return ResourceManager.GetString("OPEButton4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Download completed.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel1() As String
            Get
                Return ResourceManager.GetString("OPELabel1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel2() As String
            Get
                Return ResourceManager.GetString("OPELabel2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The file saved as.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel3() As String
            Get
                Return ResourceManager.GetString("OPELabel3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Downloaded.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel5() As String
            Get
                Return ResourceManager.GetString("OPELabel5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Open folder.
        '''</summary>
        Friend Shared ReadOnly Property OpenFolderToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenFolderToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Open app.
        '''</summary>
        Friend Shared ReadOnly Property OpenSDMToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenSDMToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend Shared ReadOnly Property OpenToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Open with....
        '''</summary>
        Friend Shared ReadOnly Property OpenWithToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenWithToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Option.
        '''</summary>
        Friend Shared ReadOnly Property OPfrmoption() As String
            Get
                Return ResourceManager.GetString("OPfrmoption", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to General Settings.
        '''</summary>
        Friend Shared ReadOnly Property OPGroupBox1() As String
            Get
                Return ResourceManager.GetString("OPGroupBox1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Select sounds and events.
        '''</summary>
        Friend Shared ReadOnly Property OPGroupBox2() As String
            Get
                Return ResourceManager.GetString("OPGroupBox2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Select font and other settings for UI.
        '''</summary>
        Friend Shared ReadOnly Property OPGroupBox4() As String
            Get
                Return ResourceManager.GetString("OPGroupBox4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to General Setting.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel1() As String
            Get
                Return ResourceManager.GetString("OPLabel1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to User interface setting.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel11() As String
            Get
                Return ResourceManager.GetString("OPLabel11", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to If you change the number of connections, all downloads will be download from beginning.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel12() As String
            Get
                Return ResourceManager.GetString("OPLabel12", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Auto Reset download duration.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel13() As String
            Get
                Return ResourceManager.GetString("OPLabel13", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Second.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel14() As String
            Get
                Return ResourceManager.GetString("OPLabel14", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Cache Size.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel15() As String
            Get
                Return ResourceManager.GetString("OPLabel15", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Sounds Setting.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel3() As String
            Get
                Return ResourceManager.GetString("OPLabel3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Usernames and passwords for servers/sites.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel5() As String
            Get
                Return ResourceManager.GetString("OPLabel5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Downloaded file types.
        '''</summary>
        Friend Shared ReadOnly Property opLabel8() As String
            Get
                Return ResourceManager.GetString("opLabel8", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Connections number.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel9() As String
            Get
                Return ResourceManager.GetString("OPLabel9", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Checking , Please wait ....
        '''</summary>
        Friend Shared ReadOnly Property OPlblcheck() As String
            Get
                Return ResourceManager.GetString("OPlblcheck", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Sound.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage1() As String
            Get
                Return ResourceManager.GetString("OPTabPage1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to General.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage2() As String
            Get
                Return ResourceManager.GetString("OPTabPage2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Sites logins.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage3() As String
            Get
                Return ResourceManager.GetString("OPTabPage3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to File types.
        '''</summary>
        Friend Shared ReadOnly Property opTabPage4() As String
            Get
                Return ResourceManager.GetString("opTabPage4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to User interface.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage5() As String
            Get
                Return ResourceManager.GetString("OPTabPage5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend Shared ReadOnly Property OptionToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OptionToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend Shared ReadOnly Property PRbtnclose() As String
            Get
                Return ResourceManager.GetString("PRbtnclose", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend Shared ReadOnly Property PRbtnopen() As String
            Get
                Return ResourceManager.GetString("PRbtnopen", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend Shared ReadOnly Property PRbtnopenlink() As String
            Get
                Return ResourceManager.GetString("PRbtnopenlink", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to File Properties.
        '''</summary>
        Friend Shared ReadOnly Property PRfrmpropertise() As String
            Get
                Return ResourceManager.GetString("PRfrmpropertise", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Type :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel1() As String
            Get
                Return ResourceManager.GetString("PRLabel1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Result :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel10() As String
            Get
                Return ResourceManager.GetString("PRLabel10", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Referer :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel14() As String
            Get
                Return ResourceManager.GetString("PRLabel14", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Status :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel2() As String
            Get
                Return ResourceManager.GetString("PRLabel2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Size :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel3() As String
            Get
                Return ResourceManager.GetString("PRLabel3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Save to :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel4() As String
            Get
                Return ResourceManager.GetString("PRLabel4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Address :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel5() As String
            Get
                Return ResourceManager.GetString("PRLabel5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Description :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel6() As String
            Get
                Return ResourceManager.GetString("PRLabel6", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Login :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel7() As String
            Get
                Return ResourceManager.GetString("PRLabel7", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Password :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel8() As String
            Get
                Return ResourceManager.GetString("PRLabel8", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Last try date :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel9() As String
            Get
                Return ResourceManager.GetString("PRLabel9", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to properties.
        '''</summary>
        Friend Shared ReadOnly Property PropertiseToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("PropertiseToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Redownload.
        '''</summary>
        Friend Shared ReadOnly Property RedownloadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("RedownloadToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property RemoveToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("RemoveToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Resume download.
        '''</summary>
        Friend Shared ReadOnly Property ResumeDownloadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ResumeDownloadToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnapply() As String
            Get
                Return ResourceManager.GetString("SCbtnapply", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Hide.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnclose() As String
            Get
                Return ResourceManager.GetString("SCbtnclose", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnexit() As String
            Get
                Return ResourceManager.GetString("SCbtnexit", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Start now.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnstart() As String
            Get
                Return ResourceManager.GetString("SCbtnstart", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Stop.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnstop() As String
            Get
                Return ResourceManager.GetString("SCbtnstop", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property SCCdescriptionl() As String
            Get
                Return ResourceManager.GetString("SCCdescriptionl", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Exit SD Download Manager when done.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckexit() As String
            Get
                Return ResourceManager.GetString("SCcheckexit", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Friday.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckfriday() As String
            Get
                Return ResourceManager.GetString("SCcheckfriday", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Hang up modem when done.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckhangmodem() As String
            Get
                Return ResourceManager.GetString("SCcheckhangmodem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Monday.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckmonday() As String
            Get
                Return ResourceManager.GetString("SCcheckmonday", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Open the following file when done.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckopenfile() As String
            Get
                Return ResourceManager.GetString("SCcheckopenfile", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Number of retries for each files if downloading faild :.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckretrycount() As String
            Get
                Return ResourceManager.GetString("SCcheckretrycount", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Saturday.
        '''</summary>
        Friend Shared ReadOnly Property SCchecksaturday() As String
            Get
                Return ResourceManager.GetString("SCchecksaturday", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Start download at.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckstarttime() As String
            Get
                Return ResourceManager.GetString("SCcheckstarttime", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Start download on SD Download Manager startup.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckstartup() As String
            Get
                Return ResourceManager.GetString("SCcheckstartup", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Stop download at.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckstoptime() As String
            Get
                Return ResourceManager.GetString("SCcheckstoptime", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Sunday.
        '''</summary>
        Friend Shared ReadOnly Property SCchecksunday() As String
            Get
                Return ResourceManager.GetString("SCchecksunday", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Thursday.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckthursday() As String
            Get
                Return ResourceManager.GetString("SCcheckthursday", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Tuesday.
        '''</summary>
        Friend Shared ReadOnly Property SCchecktuesday() As String
            Get
                Return ResourceManager.GetString("SCchecktuesday", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Turn off computer when done.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckturnoff() As String
            Get
                Return ResourceManager.GetString("SCcheckturnoff", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Wednesday.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckwednesday() As String
            Get
                Return ResourceManager.GetString("SCcheckwednesday", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property SCCidl() As String
            Get
                Return ResourceManager.GetString("SCCidl", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Last try date.
        '''</summary>
        Friend Shared ReadOnly Property SCClasttryl() As String
            Get
                Return ResourceManager.GetString("SCClasttryl", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Time left .
        '''</summary>
        Friend Shared ReadOnly Property SCClefttimel() As String
            Get
                Return ResourceManager.GetString("SCClefttimel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Link.
        '''</summary>
        Friend Shared ReadOnly Property SCClinkl() As String
            Get
                Return ResourceManager.GetString("SCClinkl", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property SCCNamel() As String
            Get
                Return ResourceManager.GetString("SCCNamel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property SCCpasswordl() As String
            Get
                Return ResourceManager.GetString("SCCpasswordl", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Save to.
        '''</summary>
        Friend Shared ReadOnly Property SCCsavetol() As String
            Get
                Return ResourceManager.GetString("SCCsavetol", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Size.
        '''</summary>
        Friend Shared ReadOnly Property SCCsizel() As String
            Get
                Return ResourceManager.GetString("SCCsizel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Speed.
        '''</summary>
        Friend Shared ReadOnly Property SCCSpeedl() As String
            Get
                Return ResourceManager.GetString("SCCSpeedl", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property SCCstatusl() As String
            Get
                Return ResourceManager.GetString("SCCstatusl", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to User name.
        '''</summary>
        Friend Shared ReadOnly Property SCCusernamel() As String
            Get
                Return ResourceManager.GetString("SCCusernamel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Downloaded :.
        '''</summary>
        Friend Shared ReadOnly Property SCdledlbl() As String
            Get
                Return ResourceManager.GetString("SCdledlbl", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Force processes to terminate.
        '''</summary>
        Friend Shared ReadOnly Property SCforceturnoffcheck() As String
            Get
                Return ResourceManager.GetString("SCforceturnoffcheck", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Scheduler.
        '''</summary>
        Friend Shared ReadOnly Property SCfrmschedule() As String
            Get
                Return ResourceManager.GetString("SCfrmschedule", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Schedule.
        '''</summary>
        Friend Shared ReadOnly Property ScheduleToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ScheduleToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Download.
        '''</summary>
        Friend Shared ReadOnly Property SCLabel3() As String
            Get
                Return ResourceManager.GetString("SCLabel3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to file at the some time.
        '''</summary>
        Friend Shared ReadOnly Property SCLabel4() As String
            Get
                Return ResourceManager.GetString("SCLabel4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Daily.
        '''</summary>
        Friend Shared ReadOnly Property SCrbdayli() As String
            Get
                Return ResourceManager.GetString("SCrbdayli", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Once at.
        '''</summary>
        Friend Shared ReadOnly Property SCrbonce() As String
            Get
                Return ResourceManager.GetString("SCrbonce", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to remaining :.
        '''</summary>
        Friend Shared ReadOnly Property SCremainlbl() As String
            Get
                Return ResourceManager.GetString("SCremainlbl", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Schedule.
        '''</summary>
        Friend Shared ReadOnly Property SCTabPage1() As String
            Get
                Return ResourceManager.GetString("SCTabPage1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Files in the queue.
        '''</summary>
        Friend Shared ReadOnly Property SCTabPage2() As String
            Get
                Return ResourceManager.GetString("SCTabPage2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Show Category.
        '''</summary>
        Friend Shared ReadOnly Property ShowCategoryToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ShowCategoryToolStripMenuItem", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Hide Category.
        '''</summary>
        Friend Shared ReadOnly Property ShowCategoryToolStripMenuItemhide() As String
            Get
                Return ResourceManager.GetString("ShowCategoryToolStripMenuItemhide", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Show drop target.
        '''</summary>
        Friend Shared ReadOnly Property ShowDropTargetToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ShowDropTargetToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Small.
        '''</summary>
        Friend Shared ReadOnly Property SmallToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("SmallToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop download.
        '''</summary>
        Friend Shared ReadOnly Property StopDownloadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("StopDownloadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canceled.
        '''</summary>
        Friend Shared ReadOnly Property stsCanceled() As String
            Get
                Return ResourceManager.GetString("stsCanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canceling.
        '''</summary>
        Friend Shared ReadOnly Property stsCanceling() As String
            Get
                Return ResourceManager.GetString("stsCanceling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completed.
        '''</summary>
        Friend Shared ReadOnly Property stsCompleted() As String
            Get
                Return ResourceManager.GetString("stsCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connecting ....
        '''</summary>
        Friend Shared ReadOnly Property stsConnecting() As String
            Get
                Return ResourceManager.GetString("stsConnecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download faild.
        '''</summary>
        Friend Shared ReadOnly Property stsDLfaild() As String
            Get
                Return ResourceManager.GetString("stsDLfaild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download faild - Trying again to download.
        '''</summary>
        Friend Shared ReadOnly Property stsDLfaild_Tryingagain() As String
            Get
                Return ResourceManager.GetString("stsDLfaild_Tryingagain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download resetted.
        '''</summary>
        Friend Shared ReadOnly Property stsDLresetted() As String
            Get
                Return ResourceManager.GetString("stsDLresetted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resetting download....
        '''</summary>
        Friend Shared ReadOnly Property stsDLresetting() As String
            Get
                Return ResourceManager.GetString("stsDLresetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading.
        '''</summary>
        Friend Shared ReadOnly Property stsDownloading() As String
            Get
                Return ResourceManager.GetString("stsDownloading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Faild.
        '''</summary>
        Friend Shared ReadOnly Property stsfaild() As String
            Get
                Return ResourceManager.GetString("stsfaild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File succesfully downloaded and merged.
        '''</summary>
        Friend Shared ReadOnly Property stsMerged() As String
            Get
                Return ResourceManager.GetString("stsMerged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merging downloaded parts - Please wait....
        '''</summary>
        Friend Shared ReadOnly Property stsMergin() As String
            Get
                Return ResourceManager.GetString("stsMergin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paused.
        '''</summary>
        Friend Shared ReadOnly Property stsPaused() As String
            Get
                Return ResourceManager.GetString("stsPaused", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pausing.
        '''</summary>
        Friend Shared ReadOnly Property stsPausing() As String
            Get
                Return ResourceManager.GetString("stsPausing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting download.
        '''</summary>
        Friend Shared ReadOnly Property stsStarting() As String
            Get
                Return ResourceManager.GetString("stsStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloads.
        '''</summary>
        Friend Shared ReadOnly Property TabPage1() As String
            Get
                Return ResourceManager.GetString("TabPage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logs.
        '''</summary>
        Friend Shared ReadOnly Property TabPage2() As String
            Get
                Return ResourceManager.GetString("TabPage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Redownload.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem10() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pause All.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem12() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop All.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem13() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem3() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem4() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add new link.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem5() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem6() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop download.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem7() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem8() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property UPbtncancel() As String
            Get
                Return ResourceManager.GetString("UPbtncancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property UPbtnok() As String
            Get
                Return ResourceManager.GetString("UPbtnok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Site login.
        '''</summary>
        Friend Shared ReadOnly Property UPEfrmuserpass() As String
            Get
                Return ResourceManager.GetString("UPEfrmuserpass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server/Path.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel1() As String
            Get
                Return ResourceManager.GetString("UPELabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note : Type the path only if you have different login names for different server directories.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel2() As String
            Get
                Return ResourceManager.GetString("UPELabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User name.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel3() As String
            Get
                Return ResourceManager.GetString("UPELabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel4() As String
            Get
                Return ResourceManager.GetString("UPELabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Site login.
        '''</summary>
        Friend Shared ReadOnly Property UPfrmuserpass() As String
            Get
                Return ResourceManager.GetString("UPfrmuserpass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server/Path.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel1() As String
            Get
                Return ResourceManager.GetString("UPLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note : Type the path only if you have different login names for different server directories.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel2() As String
            Get
                Return ResourceManager.GetString("UPLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User name.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel3() As String
            Get
                Return ResourceManager.GetString("UPLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel4() As String
            Get
                Return ResourceManager.GetString("UPLabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View.
        '''</summary>
        Friend Shared ReadOnly Property ViewToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ViewToolStripMenuItem", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
