'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class FA
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SD_Download_Manager.FA", GetType(FA).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to درباره.
        '''</summary>
        Friend Shared ReadOnly Property AboutToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("AboutToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to درباره.
        '''</summary>
        Friend Shared ReadOnly Property AboutToolStripMenuItem1() As String
            Get
                Return ResourceManager.GetString("AboutToolStripMenuItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to باشه.
        '''</summary>
        Friend Shared ReadOnly Property ADButton1() As String
            Get
                Return ResourceManager.GetString("ADButton1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انصراف.
        '''</summary>
        Friend Shared ReadOnly Property ADButton2() As String
            Get
                Return ResourceManager.GetString("ADButton2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بعدا دانلود کن.
        '''</summary>
        Friend Shared ReadOnly Property ADchdlnow() As String
            Get
                Return ResourceManager.GetString("ADchdlnow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to استفاده از مسیر پیشفرض.
        '''</summary>
        Friend Shared ReadOnly Property ADchdpath() As String
            Get
                Return ResourceManager.GetString("ADchdpath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to استفاده از حساب کاربری.
        '''</summary>
        Friend Shared ReadOnly Property ADCheckBox1() As String
            Get
                Return ResourceManager.GetString("ADCheckBox1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  به یاد داشته باش &lt;Category&gt; این مسیر را برای دسته‌بندی.
        '''</summary>
        Friend Shared ReadOnly Property ADCheckRemember() As String
            Get
                Return ResourceManager.GetString("ADCheckRemember", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اضافه کردن لینک.
        '''</summary>
        Friend Shared ReadOnly Property Addlink() As String
            Get
                Return ResourceManager.GetString("Addlink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اضافه کردن لینک جدید.
        '''</summary>
        Friend Shared ReadOnly Property AddLinkToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("AddLinkToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آدرس :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel1() As String
            Get
                Return ResourceManager.GetString("ADLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام کاربری :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel2() As String
            Get
                Return ResourceManager.GetString("ADLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رمز عبور :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel3() As String
            Get
                Return ResourceManager.GetString("ADLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel5() As String
            Get
                Return ResourceManager.GetString("ADLabel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توضیحات :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel6() As String
            Get
                Return ResourceManager.GetString("ADLabel6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام فایل :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel7() As String
            Get
                Return ResourceManager.GetString("ADLabel7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دسته‌بندی.
        '''</summary>
        Friend Shared ReadOnly Property ADlblCategory() As String
            Get
                Return ResourceManager.GetString("ADlblCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توضیحات.
        '''</summary>
        Friend Shared ReadOnly Property ADlbldescription() As String
            Get
                Return ResourceManager.GetString("ADlbldescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مرتب کردن فایل ها.
        '''</summary>
        Friend Shared ReadOnly Property ArrangeFilesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ArrangeFilesToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بر اساس نام.
        '''</summary>
        Friend Shared ReadOnly Property ByFileNameToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByFileNameToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بر اساس شماره.
        '''</summary>
        Friend Shared ReadOnly Property ByIDToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByIDToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بر اساس آخرین تاریخ دانلود.
        '''</summary>
        Friend Shared ReadOnly Property ByLastTryDateToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByLastTryDateToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بر اساس زمان باقیمانده.
        '''</summary>
        Friend Shared ReadOnly Property ByLeftTimeToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByLeftTimeToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بر اساس حجم.
        '''</summary>
        Friend Shared ReadOnly Property BySizeToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("BySizeToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بر اساس وضعیت دانلود.
        '''</summary>
        Friend Shared ReadOnly Property ByStatusToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByStatusToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بر اساس سرعت.
        '''</summary>
        Friend Shared ReadOnly Property ByToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to استفاده از پروکسی سیستم.
        '''</summary>
        Friend Shared ReadOnly Property checkuseproxy() As String
            Get
                Return ResourceManager.GetString("checkuseproxy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان آخرین تلاش.
        '''</summary>
        Friend Shared ReadOnly Property CLdate() As String
            Get
                Return ResourceManager.GetString("CLdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توضیحات.
        '''</summary>
        Friend Shared ReadOnly Property CLDescription() As String
            Get
                Return ResourceManager.GetString("CLDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to لینک.
        '''</summary>
        Friend Shared ReadOnly Property CLink() As String
            Get
                Return ResourceManager.GetString("CLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام.
        '''</summary>
        Friend Shared ReadOnly Property CLname() As String
            Get
                Return ResourceManager.GetString("CLname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شماره.
        '''</summary>
        Friend Shared ReadOnly Property CLnomber() As String
            Get
                Return ResourceManager.GetString("CLnomber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رمز عبور.
        '''</summary>
        Friend Shared ReadOnly Property CLpassword() As String
            Get
                Return ResourceManager.GetString("CLpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سایز.
        '''</summary>
        Friend Shared ReadOnly Property CLsize() As String
            Get
                Return ResourceManager.GetString("CLsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سرعت.
        '''</summary>
        Friend Shared ReadOnly Property CLspeed() As String
            Get
                Return ResourceManager.GetString("CLspeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to وضعیت.
        '''</summary>
        Friend Shared ReadOnly Property CLstatus() As String
            Get
                Return ResourceManager.GetString("CLstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان باقیمانده.
        '''</summary>
        Friend Shared ReadOnly Property CLtime() As String
            Get
                Return ResourceManager.GetString("CLtime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام کاربری.
        '''</summary>
        Friend Shared ReadOnly Property CLusername() As String
            Get
                Return ResourceManager.GetString("CLusername", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نه خیر.
        '''</summary>
        Friend Shared ReadOnly Property DELbtnno() As String
            Get
                Return ResourceManager.GetString("DELbtnno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بله.
        '''</summary>
        Friend Shared ReadOnly Property DELbtnyes() As String
            Get
                Return ResourceManager.GetString("DELbtnyes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to این پنجره را دیگر نشان نده.
        '''</summary>
        Friend Shared ReadOnly Property DELcheckdontshow() As String
            Get
                Return ResourceManager.GetString("DELcheckdontshow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حذف تکمیلها.
        '''</summary>
        Friend Shared ReadOnly Property DeleteAllcompletedToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("DeleteAllcompletedToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیا از پاک کردن این فایل  مطمئن هستید ؟.
        '''</summary>
        Friend Shared ReadOnly Property DELLabel1() As String
            Get
                Return ResourceManager.GetString("DELLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to درخواست پاک کردن.
        '''</summary>
        Friend Shared ReadOnly Property DELmsgdelete() As String
            Get
                Return ResourceManager.GetString("DELmsgdelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ایست.
        '''</summary>
        Friend Shared ReadOnly Property DLbtnpause() As String
            Get
                Return ResourceManager.GetString("DLbtnpause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ادامه.
        '''</summary>
        Friend Shared ReadOnly Property DLbtnresume() As String
            Get
                Return ResourceManager.GetString("DLbtnresume", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توقف.
        '''</summary>
        Friend Shared ReadOnly Property DLbtnstop() As String
            Get
                Return ResourceManager.GetString("DLbtnstop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;&lt; پنهان کردن جزئیات.
        '''</summary>
        Friend Shared ReadOnly Property DLclosetext() As String
            Get
                Return ResourceManager.GetString("DLclosetext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بعد از اتمام دانلودها , برنامه را ببند.
        '''</summary>
        Friend Shared ReadOnly Property DLexitchek() As String
            Get
                Return ResourceManager.GetString("DLexitchek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to برنامه های درحال اجرا را مجبور به بستن کن.
        '''</summary>
        Friend Shared ReadOnly Property DLforceturnoffcheck() As String
            Get
                Return ResourceManager.GetString("DLforceturnoffcheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود شده .
        '''</summary>
        Friend Shared ReadOnly Property DLl1() As String
            Get
                Return ResourceManager.GetString("DLl1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to وضعیت .
        '''</summary>
        Friend Shared ReadOnly Property DLl2() As String
            Get
                Return ResourceManager.GetString("DLl2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سایز فایل.
        '''</summary>
        Friend Shared ReadOnly Property DLl3() As String
            Get
                Return ResourceManager.GetString("DLl3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سرعت .
        '''</summary>
        Friend Shared ReadOnly Property DLl4() As String
            Get
                Return ResourceManager.GetString("DLl4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان باقیمانده .
        '''</summary>
        Friend Shared ReadOnly Property DLl5() As String
            Get
                Return ResourceManager.GetString("DLl5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نوع فایل .
        '''</summary>
        Friend Shared ReadOnly Property DLLabel10() As String
            Get
                Return ResourceManager.GetString("DLLabel10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to قابلیت ادامه.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel14() As String
            Get
                Return ResourceManager.GetString("DLLabel14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان سپری شده.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel15() As String
            Get
                Return ResourceManager.GetString("DLLabel15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کل بخش ها.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel16() As String
            Get
                Return ResourceManager.GetString("DLLabel16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بخش جاری.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel17() As String
            Get
                Return ResourceManager.GetString("DLLabel17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ذخیره در .
        '''</summary>
        Friend Shared ReadOnly Property DLLabel7() As String
            Get
                Return ResourceManager.GetString("DLLabel7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تنظمات زیر هنگامی که گزینه &quot;نشان دادن پنجره اتمام دانلود &quot;فعال می باشد , نمایش داده نمی شوند.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel9() As String
            Get
                Return ResourceManager.GetString("DLLabel9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود شده.
        '''</summary>
        Friend Shared ReadOnly Property DLList1Downloaded() As String
            Get
                Return ResourceManager.GetString("DLList1Downloaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شناسه.
        '''</summary>
        Friend Shared ReadOnly Property DLList1ID() As String
            Get
                Return ResourceManager.GetString("DLList1ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to وضعیت.
        '''</summary>
        Friend Shared ReadOnly Property DLList1sts() As String
            Get
                Return ResourceManager.GetString("DLList1sts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نمایش جزئیات &gt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property DLopentext() As String
            Get
                Return ResourceManager.GetString("DLopentext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to گزینه های اتمام دانلود.
        '''</summary>
        Friend Shared ReadOnly Property DLoptiontab() As String
            Get
                Return ResourceManager.GetString("DLoptiontab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بعد از اتمام دانلودها , کامپیوتر را خاموش کن.
        '''</summary>
        Friend Shared ReadOnly Property DLpcturnoffchek() As String
            Get
                Return ResourceManager.GetString("DLpcturnoffchek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نشان داده پنجره اتمام دانلود.
        '''</summary>
        Friend Shared ReadOnly Property DLshowdialogchk() As String
            Get
                Return ResourceManager.GetString("DLshowdialogchk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to وضعیت دانلود.
        '''</summary>
        Friend Shared ReadOnly Property DLstatustab() As String
            Get
                Return ResourceManager.GetString("DLstatustab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ویرایش خصوصیات دسته‌بندی.
        '''</summary>
        Friend Shared ReadOnly Property EditCat() As String
            Get
                Return ResourceManager.GetString("EditCat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام دسته‌بندی.
        '''</summary>
        Friend Shared ReadOnly Property EditCatLabel1() As String
            Get
                Return ResourceManager.GetString("EditCatLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to فایل‌هایی که دارای پسوندهای زیر می‌باشند در این دسته‌بندی قرار بده :.
        '''</summary>
        Friend Shared ReadOnly Property EditCatLabel2() As String
            Get
                Return ResourceManager.GetString("EditCatLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  (avi mpg mpeg توجه: پسوند فایل‌ها را با فاصله از هم جدا کنید(مانند .
        '''</summary>
        Friend Shared ReadOnly Property EditCatLabel3() As String
            Get
                Return ResourceManager.GetString("EditCatLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to فایل‌هایی که در این دسته‌بندی دانلود می‌شوند را در این مسیر قرار بده :.
        '''</summary>
        Friend Shared ReadOnly Property EditCatLabel5() As String
            Get
                Return ResourceManager.GetString("EditCatLabel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to خروج.
        '''</summary>
        Friend Shared ReadOnly Property ExitToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بستن.
        '''</summary>
        Friend Shared ReadOnly Property FDbtnclose() As String
            Get
                Return ResourceManager.GetString("FDbtnclose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ارسال.
        '''</summary>
        Friend Shared ReadOnly Property FDbtnersal() As String
            Get
                Return ResourceManager.GetString("FDbtnersal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to وبلاگ.
        '''</summary>
        Friend Shared ReadOnly Property FDbtnweb() As String
            Get
                Return ResourceManager.GetString("FDbtnweb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to لطفا نام و آدرس پست الکترونیک خود را وارد نمایید.
        '''</summary>
        Friend Shared ReadOnly Property FDGroupBox1() As String
            Get
                Return ResourceManager.GetString("FDGroupBox1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to لطفا نظرات ، پیشنهادات و اشکالات نرم افزار را در پایین نوشته و سپس بر روی دکمه &quot;ارسال&quot; کلیک نمایید.
        '''</summary>
        Friend Shared ReadOnly Property FDGroupBox2() As String
            Get
                Return ResourceManager.GetString("FDGroupBox2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ضمیمه :.
        '''</summary>
        Friend Shared ReadOnly Property FDlblattach() As String
            Get
                Return ResourceManager.GetString("FDlblattach", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to پست الکترونیک .
        '''</summary>
        Friend Shared ReadOnly Property FDlblmail() As String
            Get
                Return ResourceManager.GetString("FDlblmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام .
        '''</summary>
        Friend Shared ReadOnly Property FDlblname() As String
            Get
                Return ResourceManager.GetString("FDlblname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to موضوع .
        '''</summary>
        Friend Shared ReadOnly Property FDlblsubject() As String
            Get
                Return ResourceManager.GetString("FDlblsubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to باز خورد.
        '''</summary>
        Friend Shared ReadOnly Property FeedbackToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("FeedbackToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to فایل.
        '''</summary>
        Friend Shared ReadOnly Property FilesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("FilesToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کمک.
        '''</summary>
        Friend Shared ReadOnly Property HelpToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("HelpToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیکون ها.
        '''</summary>
        Friend Shared ReadOnly Property IconsToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("IconsToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بازخورد.
        '''</summary>
        Friend Shared ReadOnly Property Label10() As String
            Get
                Return ResourceManager.GetString("Label10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سبد پرتاب.
        '''</summary>
        Friend Shared ReadOnly Property Label11() As String
            Get
                Return ResourceManager.GetString("Label11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اضافه کردن لینک.
        '''</summary>
        Friend Shared ReadOnly Property Label2() As String
            Get
                Return ResourceManager.GetString("Label2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ادامه.
        '''</summary>
        Friend Shared ReadOnly Property Label3() As String
            Get
                Return ResourceManager.GetString("Label3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توقف.
        '''</summary>
        Friend Shared ReadOnly Property Label4() As String
            Get
                Return ResourceManager.GetString("Label4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توقف همه.
        '''</summary>
        Friend Shared ReadOnly Property Label5() As String
            Get
                Return ResourceManager.GetString("Label5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان بندی.
        '''</summary>
        Friend Shared ReadOnly Property Label6() As String
            Get
                Return ResourceManager.GetString("Label6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حذف.
        '''</summary>
        Friend Shared ReadOnly Property Label7() As String
            Get
                Return ResourceManager.GetString("Label7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حذف تکمیلها.
        '''</summary>
        Friend Shared ReadOnly Property Label8() As String
            Get
                Return ResourceManager.GetString("Label8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تنظیمات.
        '''</summary>
        Friend Shared ReadOnly Property Label9() As String
            Get
                Return ResourceManager.GetString("Label9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زبان.
        '''</summary>
        Friend Shared ReadOnly Property LanguageToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("LanguageToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ذخیره در.
        '''</summary>
        Friend Shared ReadOnly Property Llocation() As String
            Get
                Return ResourceManager.GetString("Llocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اتصال اینترنت برقرار نمیباشد ، لطفا پس از اطمینان از وصل بودن اینترنت مجدداٌ امتحان نمایید.
        '''</summary>
        Friend Shared ReadOnly Property NoInternet() As String
            Get
                Return ResourceManager.GetString("NoInternet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to عادی.
        '''</summary>
        Friend Shared ReadOnly Property NormalToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("NormalToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انصراف.
        '''</summary>
        Friend Shared ReadOnly Property OPbtncancel() As String
            Get
                Return ResourceManager.GetString("OPbtncancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چک کردن برای ورژن جدید.
        '''</summary>
        Friend Shared ReadOnly Property OPbtncheckfornewversion() As String
            Get
                Return ResourceManager.GetString("OPbtncheckfornewversion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ویرایش.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnedit() As String
            Get
                Return ResourceManager.GetString("OPbtnedit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جدید.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnnew() As String
            Get
                Return ResourceManager.GetString("OPbtnnew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to باشه.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnok() As String
            Get
                Return ResourceManager.GetString("OPbtnok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حذف.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnremove() As String
            Get
                Return ResourceManager.GetString("OPbtnremove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اضافه.
        '''</summary>
        Friend Shared ReadOnly Property opButton1() As String
            Get
                Return ResourceManager.GetString("opButton1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to پیش فرض.
        '''</summary>
        Friend Shared ReadOnly Property opButton2() As String
            Get
                Return ResourceManager.GetString("opButton2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حذف.
        '''</summary>
        Friend Shared ReadOnly Property opButton3() As String
            Get
                Return ResourceManager.GetString("opButton3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انتخاب فونت.
        '''</summary>
        Friend Shared ReadOnly Property OPButton4() As String
            Get
                Return ResourceManager.GetString("OPButton4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انتخاب رنگ نوشته ها.
        '''</summary>
        Friend Shared ReadOnly Property OPButton5() As String
            Get
                Return ResourceManager.GetString("OPButton5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انتخاب رنگ پس زمینه فرم ها.
        '''</summary>
        Friend Shared ReadOnly Property OPButton6() As String
            Get
                Return ResourceManager.GetString("OPButton6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بازیابی پیش فرض.
        '''</summary>
        Friend Shared ReadOnly Property OPButton7() As String
            Get
                Return ResourceManager.GetString("OPButton7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چک کردن برای آپدیت ها به صورت اتوماتیک.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckautoupdate() As String
            Get
                Return ResourceManager.GetString("OPcheckautoupdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود ناموفق.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckcancelled() As String
            Get
                Return ResourceManager.GetString("OPcheckcancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود پایان یافت.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckcompleted() As String
            Get
                Return ResourceManager.GetString("OPcheckcompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to استفاده از مسیر پیشفرض برای دانلودها.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckdefaultpath() As String
            Get
                Return ResourceManager.GetString("OPcheckdefaultpath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to پنجره درخواست پاک کردن را نمایش نده.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckdontshoedelete() As String
            Get
                Return ResourceManager.GetString("OPcheckdontshoedelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to لینکهای موجود در حافظه(کلیپ برد ویندوز) را به صورت اتوماتیک دانلود کن.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckgrabfromclipboard() As String
            Get
                Return ResourceManager.GetString("OPcheckgrabfromclipboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to استفاده از آیکون های قدیمی.
        '''</summary>
        Friend Shared ReadOnly Property OPCheckOldIcons() As String
            Get
                Return ResourceManager.GetString("OPCheckOldIcons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نشان دادن اطلاع رسانی ویندوز در هنگام اتمام دانلود.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckshownotification() As String
            Get
                Return ResourceManager.GetString("OPcheckshownotification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SD Download Manager را در هنگام بالا آمدن ویندوز اجرا کن.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckstartup() As String
            Get
                Return ResourceManager.GetString("OPcheckstartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود فایل های با پسوندهای زیر را فقط به صورت خودکار شروع کن.
        '''</summary>
        Friend Shared ReadOnly Property opcheckusefiletype() As String
            Get
                Return ResourceManager.GetString("opcheckusefiletype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رمز عبور.
        '''</summary>
        Friend Shared ReadOnly Property OPCpass() As String
            Get
                Return ResourceManager.GetString("OPCpass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سایت/مسیر.
        '''</summary>
        Friend Shared ReadOnly Property OPCsite() As String
            Get
                Return ResourceManager.GetString("OPCsite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام کاربری.
        '''</summary>
        Friend Shared ReadOnly Property OPCuser() As String
            Get
                Return ResourceManager.GetString("OPCuser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بازکردن با.
        '''</summary>
        Friend Shared ReadOnly Property OPEbtnopenwith() As String
            Get
                Return ResourceManager.GetString("OPEbtnopenwith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بازکردن/اجرا.
        '''</summary>
        Friend Shared ReadOnly Property OPEButton1() As String
            Get
                Return ResourceManager.GetString("OPEButton1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بازکردن پوشه.
        '''</summary>
        Friend Shared ReadOnly Property OPEButton3() As String
            Get
                Return ResourceManager.GetString("OPEButton3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بستن.
        '''</summary>
        Friend Shared ReadOnly Property OPEButton4() As String
            Get
                Return ResourceManager.GetString("OPEButton4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود پایان یافت.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel1() As String
            Get
                Return ResourceManager.GetString("OPELabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آدرس.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel2() As String
            Get
                Return ResourceManager.GetString("OPELabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ذخیره شده در.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel3() As String
            Get
                Return ResourceManager.GetString("OPELabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود شده.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel5() As String
            Get
                Return ResourceManager.GetString("OPELabel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بازکردن پوشه.
        '''</summary>
        Friend Shared ReadOnly Property OpenFolderToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenFolderToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بازکردن برنامه.
        '''</summary>
        Friend Shared ReadOnly Property OpenSDMToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenSDMToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بازکردن.
        '''</summary>
        Friend Shared ReadOnly Property OpenToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بازکردن با....
        '''</summary>
        Friend Shared ReadOnly Property OpenWithToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenWithToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تنظیمات.
        '''</summary>
        Friend Shared ReadOnly Property OPfrmoption() As String
            Get
                Return ResourceManager.GetString("OPfrmoption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تنظیمات اصلی.
        '''</summary>
        Friend Shared ReadOnly Property OPGroupBox1() As String
            Get
                Return ResourceManager.GetString("OPGroupBox1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to صدا و رویداد را انتخاب کنید.
        '''</summary>
        Friend Shared ReadOnly Property OPGroupBox2() As String
            Get
                Return ResourceManager.GetString("OPGroupBox2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انتخاب فونت و تنظیمات دیگر برای رابط کاربری.
        '''</summary>
        Friend Shared ReadOnly Property OPGroupBox4() As String
            Get
                Return ResourceManager.GetString("OPGroupBox4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تنظیمات اصلی.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel1() As String
            Get
                Return ResourceManager.GetString("OPLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تنظیمات رابط کاربری.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel11() As String
            Get
                Return ResourceManager.GetString("OPLabel11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اگر تعداد ارتباطات را تغییر دهید، تمامی دانلودها از ابتدا دانلود خواهند شد.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel12() As String
            Get
                Return ResourceManager.GetString("OPLabel12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مدت ریسِت اتوماتیک دانلود.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel13() As String
            Get
                Return ResourceManager.GetString("OPLabel13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ثانیه.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel14() As String
            Get
                Return ResourceManager.GetString("OPLabel14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اندازه کش.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel15() As String
            Get
                Return ResourceManager.GetString("OPLabel15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تنظیمات صدا.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel3() As String
            Get
                Return ResourceManager.GetString("OPLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام کاربری و رمز عبور برای سرورها/سایت ها.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel5() As String
            Get
                Return ResourceManager.GetString("OPLabel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نوع فایل های دانلود شده.
        '''</summary>
        Friend Shared ReadOnly Property opLabel8() As String
            Get
                Return ResourceManager.GetString("opLabel8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تعداد ارتباطات.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel9() As String
            Get
                Return ResourceManager.GetString("OPLabel9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to درحال چک کردن , لطفا صبور باشید ....
        '''</summary>
        Friend Shared ReadOnly Property OPlblcheck() As String
            Get
                Return ResourceManager.GetString("OPlblcheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to صدا.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage1() As String
            Get
                Return ResourceManager.GetString("OPTabPage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اصلی.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage2() As String
            Get
                Return ResourceManager.GetString("OPTabPage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سایت های پسورد دار.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage3() As String
            Get
                Return ResourceManager.GetString("OPTabPage3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نوع فایل ها.
        '''</summary>
        Friend Shared ReadOnly Property opTabPage4() As String
            Get
                Return ResourceManager.GetString("opTabPage4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رابط کاربری.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage5() As String
            Get
                Return ResourceManager.GetString("OPTabPage5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تنظیمات.
        '''</summary>
        Friend Shared ReadOnly Property OptionToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OptionToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بستن.
        '''</summary>
        Friend Shared ReadOnly Property PRbtnclose() As String
            Get
                Return ResourceManager.GetString("PRbtnclose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to باز کردن.
        '''</summary>
        Friend Shared ReadOnly Property PRbtnopen() As String
            Get
                Return ResourceManager.GetString("PRbtnopen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to باز کن.
        '''</summary>
        Friend Shared ReadOnly Property PRbtnopenlink() As String
            Get
                Return ResourceManager.GetString("PRbtnopenlink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مشخصات فایل.
        '''</summary>
        Friend Shared ReadOnly Property PRfrmpropertise() As String
            Get
                Return ResourceManager.GetString("PRfrmpropertise", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نوع :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel1() As String
            Get
                Return ResourceManager.GetString("PRLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نتیجه :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel10() As String
            Get
                Return ResourceManager.GetString("PRLabel10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ارجاع دهنده :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel14() As String
            Get
                Return ResourceManager.GetString("PRLabel14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to وضعیت :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel2() As String
            Get
                Return ResourceManager.GetString("PRLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سایز :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel3() As String
            Get
                Return ResourceManager.GetString("PRLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ذخیره در :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel4() As String
            Get
                Return ResourceManager.GetString("PRLabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آدرس :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel5() As String
            Get
                Return ResourceManager.GetString("PRLabel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توضیحات :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel6() As String
            Get
                Return ResourceManager.GetString("PRLabel6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام کاربری :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel7() As String
            Get
                Return ResourceManager.GetString("PRLabel7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رمز عبور :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel8() As String
            Get
                Return ResourceManager.GetString("PRLabel8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان آخرین تلاش :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel9() As String
            Get
                Return ResourceManager.GetString("PRLabel9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مشخصات.
        '''</summary>
        Friend Shared ReadOnly Property PropertiseToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("PropertiseToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود مجدد.
        '''</summary>
        Friend Shared ReadOnly Property RedownloadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("RedownloadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حذف.
        '''</summary>
        Friend Shared ReadOnly Property RemoveToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("RemoveToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ادامه دانلود.
        '''</summary>
        Friend Shared ReadOnly Property ResumeDownloadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ResumeDownloadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اجرا.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnapply() As String
            Get
                Return ResourceManager.GetString("SCbtnapply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to پنهان .
        '''</summary>
        Friend Shared ReadOnly Property SCbtnclose() As String
            Get
                Return ResourceManager.GetString("SCbtnclose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ببند.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnexit() As String
            Get
                Return ResourceManager.GetString("SCbtnexit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شروع.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnstart() As String
            Get
                Return ResourceManager.GetString("SCbtnstart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توقف.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnstop() As String
            Get
                Return ResourceManager.GetString("SCbtnstop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توضیحات.
        '''</summary>
        Friend Shared ReadOnly Property SCCdescriptionl() As String
            Get
                Return ResourceManager.GetString("SCCdescriptionl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بعد از اتمام دانلودها برنامه را ببند.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckexit() As String
            Get
                Return ResourceManager.GetString("SCcheckexit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جمعه.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckfriday() As String
            Get
                Return ResourceManager.GetString("SCcheckfriday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بعد از اتمام دانلودها , اینترنت را قطع کن.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckhangmodem() As String
            Get
                Return ResourceManager.GetString("SCcheckhangmodem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دوشنبه.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckmonday() As String
            Get
                Return ResourceManager.GetString("SCcheckmonday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to فایل زیر بعد از اتمام دانلود باز شود.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckopenfile() As String
            Get
                Return ResourceManager.GetString("SCcheckopenfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تعداد دفعات سعی مجدد برای فایلهایی که با خطا مواجه میشوند :.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckretrycount() As String
            Get
                Return ResourceManager.GetString("SCcheckretrycount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شنبه.
        '''</summary>
        Friend Shared ReadOnly Property SCchecksaturday() As String
            Get
                Return ResourceManager.GetString("SCchecksaturday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان شروع دانلود .
        '''</summary>
        Friend Shared ReadOnly Property SCcheckstarttime() As String
            Get
                Return ResourceManager.GetString("SCcheckstarttime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلودها همراه با شروع اجرای برنامه آغاز شوند.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckstartup() As String
            Get
                Return ResourceManager.GetString("SCcheckstartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to قطع دانلود در زمان.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckstoptime() As String
            Get
                Return ResourceManager.GetString("SCcheckstoptime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to یکشنبه.
        '''</summary>
        Friend Shared ReadOnly Property SCchecksunday() As String
            Get
                Return ResourceManager.GetString("SCchecksunday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to پنج شنبه.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckthursday() As String
            Get
                Return ResourceManager.GetString("SCcheckthursday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سه شنبه.
        '''</summary>
        Friend Shared ReadOnly Property SCchecktuesday() As String
            Get
                Return ResourceManager.GetString("SCchecktuesday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بعد از اتمام دانلود , کامپیوتر را خاموش کن.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckturnoff() As String
            Get
                Return ResourceManager.GetString("SCcheckturnoff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چهارشنبه.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckwednesday() As String
            Get
                Return ResourceManager.GetString("SCcheckwednesday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شماره.
        '''</summary>
        Friend Shared ReadOnly Property SCCidl() As String
            Get
                Return ResourceManager.GetString("SCCidl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان آخرین تلاش.
        '''</summary>
        Friend Shared ReadOnly Property SCClasttryl() As String
            Get
                Return ResourceManager.GetString("SCClasttryl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان باقیمانده.
        '''</summary>
        Friend Shared ReadOnly Property SCClefttimel() As String
            Get
                Return ResourceManager.GetString("SCClefttimel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to لینک.
        '''</summary>
        Friend Shared ReadOnly Property SCClinkl() As String
            Get
                Return ResourceManager.GetString("SCClinkl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام.
        '''</summary>
        Friend Shared ReadOnly Property SCCNamel() As String
            Get
                Return ResourceManager.GetString("SCCNamel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رمز عبور.
        '''</summary>
        Friend Shared ReadOnly Property SCCpasswordl() As String
            Get
                Return ResourceManager.GetString("SCCpasswordl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ذخیره در.
        '''</summary>
        Friend Shared ReadOnly Property SCCsavetol() As String
            Get
                Return ResourceManager.GetString("SCCsavetol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سایز.
        '''</summary>
        Friend Shared ReadOnly Property SCCsizel() As String
            Get
                Return ResourceManager.GetString("SCCsizel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سرعت.
        '''</summary>
        Friend Shared ReadOnly Property SCCSpeedl() As String
            Get
                Return ResourceManager.GetString("SCCSpeedl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to وضعیت.
        '''</summary>
        Friend Shared ReadOnly Property SCCstatusl() As String
            Get
                Return ResourceManager.GetString("SCCstatusl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام کاربری.
        '''</summary>
        Friend Shared ReadOnly Property SCCusernamel() As String
            Get
                Return ResourceManager.GetString("SCCusernamel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلودشده :.
        '''</summary>
        Friend Shared ReadOnly Property SCdledlbl() As String
            Get
                Return ResourceManager.GetString("SCdledlbl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to برنامه های درحال اجرا را مجبور به بستن کن.
        '''</summary>
        Friend Shared ReadOnly Property SCforceturnoffcheck() As String
            Get
                Return ResourceManager.GetString("SCforceturnoffcheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان بند.
        '''</summary>
        Friend Shared ReadOnly Property SCfrmschedule() As String
            Get
                Return ResourceManager.GetString("SCfrmschedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان بندی.
        '''</summary>
        Friend Shared ReadOnly Property ScheduleToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ScheduleToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود.
        '''</summary>
        Friend Shared ReadOnly Property SCLabel3() As String
            Get
                Return ResourceManager.GetString("SCLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود همزمان.
        '''</summary>
        Friend Shared ReadOnly Property SCLabel4() As String
            Get
                Return ResourceManager.GetString("SCLabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to روزانه.
        '''</summary>
        Friend Shared ReadOnly Property SCrbdayli() As String
            Get
                Return ResourceManager.GetString("SCrbdayli", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to یکبار در تاریخ.
        '''</summary>
        Friend Shared ReadOnly Property SCrbonce() As String
            Get
                Return ResourceManager.GetString("SCrbonce", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to باقیمانده :.
        '''</summary>
        Friend Shared ReadOnly Property SCremainlbl() As String
            Get
                Return ResourceManager.GetString("SCremainlbl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to زمان بندی.
        '''</summary>
        Friend Shared ReadOnly Property SCTabPage1() As String
            Get
                Return ResourceManager.GetString("SCTabPage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to فایل های درون صف.
        '''</summary>
        Friend Shared ReadOnly Property SCTabPage2() As String
            Get
                Return ResourceManager.GetString("SCTabPage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نمایش دسته بندی.
        '''</summary>
        Friend Shared ReadOnly Property ShowCategoryToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ShowCategoryToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مخفی‌کردن دسته بندی.
        '''</summary>
        Friend Shared ReadOnly Property ShowCategoryToolStripMenuItemhide() As String
            Get
                Return ResourceManager.GetString("ShowCategoryToolStripMenuItemhide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نمایش سبد پرتاب.
        '''</summary>
        Friend Shared ReadOnly Property ShowDropTargetToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ShowDropTargetToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کوچک.
        '''</summary>
        Friend Shared ReadOnly Property SmallToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("SmallToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توقف دانلود.
        '''</summary>
        Friend Shared ReadOnly Property StopDownloadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("StopDownloadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to لغو شده.
        '''</summary>
        Friend Shared ReadOnly Property stsCanceled() As String
            Get
                Return ResourceManager.GetString("stsCanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to در حال لغو کردن.
        '''</summary>
        Friend Shared ReadOnly Property stsCanceling() As String
            Get
                Return ResourceManager.GetString("stsCanceling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تکمیل شده.
        '''</summary>
        Friend Shared ReadOnly Property stsCompleted() As String
            Get
                Return ResourceManager.GetString("stsCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to در حال اتصال ....
        '''</summary>
        Friend Shared ReadOnly Property stsConnecting() As String
            Get
                Return ResourceManager.GetString("stsConnecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود ناموفق بود.
        '''</summary>
        Friend Shared ReadOnly Property stsDLfaild() As String
            Get
                Return ResourceManager.GetString("stsDLfaild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود ناموفق - در حال تلاش مجدد.
        '''</summary>
        Friend Shared ReadOnly Property stsDLfaild_Tryingagain() As String
            Get
                Return ResourceManager.GetString("stsDLfaild_Tryingagain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود ریست گردید.
        '''</summary>
        Friend Shared ReadOnly Property stsDLresetted() As String
            Get
                Return ResourceManager.GetString("stsDLresetted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to در حال ریست دانلود ....
        '''</summary>
        Friend Shared ReadOnly Property stsDLresetting() As String
            Get
                Return ResourceManager.GetString("stsDLresetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to در حال دریافت.
        '''</summary>
        Friend Shared ReadOnly Property stsDownloading() As String
            Get
                Return ResourceManager.GetString("stsDownloading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ناموفق.
        '''</summary>
        Friend Shared ReadOnly Property stsfaild() As String
            Get
                Return ResourceManager.GetString("stsfaild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to فایل با موفقیت دانلود و یکپارچه سازی شد.
        '''</summary>
        Friend Shared ReadOnly Property stsMerged() As String
            Get
                Return ResourceManager.GetString("stsMerged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ...در حال ادغام بخش های دانلود شده - لطفا صبر کنید.
        '''</summary>
        Friend Shared ReadOnly Property stsMergin() As String
            Get
                Return ResourceManager.GetString("stsMergin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to متوقف شده.
        '''</summary>
        Friend Shared ReadOnly Property stsPaused() As String
            Get
                Return ResourceManager.GetString("stsPaused", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to در حال توقف.
        '''</summary>
        Friend Shared ReadOnly Property stsPausing() As String
            Get
                Return ResourceManager.GetString("stsPausing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to در حال شروع دانلود ....
        '''</summary>
        Friend Shared ReadOnly Property stsStarting() As String
            Get
                Return ResourceManager.GetString("stsStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود ها.
        '''</summary>
        Friend Shared ReadOnly Property TabPage1() As String
            Get
                Return ResourceManager.GetString("TabPage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to گزارشات.
        '''</summary>
        Friend Shared ReadOnly Property TabPage2() As String
            Get
                Return ResourceManager.GetString("TabPage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود مجدد.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem10() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ایست همه.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem12() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توقف همه.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem13() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to امور.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem3() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دانلود.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem4() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اضافه کردن لینک جدید.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem5() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to خروج.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem6() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توقف دانلود.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem7() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حذف.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem8() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انصراف.
        '''</summary>
        Friend Shared ReadOnly Property UPbtncancel() As String
            Get
                Return ResourceManager.GetString("UPbtncancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to باشه.
        '''</summary>
        Friend Shared ReadOnly Property UPbtnok() As String
            Get
                Return ResourceManager.GetString("UPbtnok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ورود به سایت.
        '''</summary>
        Friend Shared ReadOnly Property UPEfrmuserpass() As String
            Get
                Return ResourceManager.GetString("UPEfrmuserpass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سرور/مسیر.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel1() As String
            Get
                Return ResourceManager.GetString("UPELabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توجه : آدرس سایت را فقط  در صورتی وارد کنید که اکانتی برای آن سایت دارید.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel2() As String
            Get
                Return ResourceManager.GetString("UPELabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام کاربری.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel3() As String
            Get
                Return ResourceManager.GetString("UPELabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رمز عبور.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel4() As String
            Get
                Return ResourceManager.GetString("UPELabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ورود به سایت.
        '''</summary>
        Friend Shared ReadOnly Property UPfrmuserpass() As String
            Get
                Return ResourceManager.GetString("UPfrmuserpass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سرور/مسیر.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel1() As String
            Get
                Return ResourceManager.GetString("UPLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توجه : آدرس سایت را فقط  در صورتی وارد کنید که اکانتی برای آن سایت دارید.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel2() As String
            Get
                Return ResourceManager.GetString("UPLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام کاربری .
        '''</summary>
        Friend Shared ReadOnly Property UPLabel3() As String
            Get
                Return ResourceManager.GetString("UPLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رمز عبور.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel4() As String
            Get
                Return ResourceManager.GetString("UPLabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نمایش.
        '''</summary>
        Friend Shared ReadOnly Property ViewToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ViewToolStripMenuItem", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
