'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class IT
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SD_Download_Manager.IT", GetType(IT).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Circa.
        '''</summary>
        Friend Shared ReadOnly Property AboutToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("AboutToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Circa.
        '''</summary>
        Friend Shared ReadOnly Property AboutToolStripMenuItem1() As String
            Get
                Return ResourceManager.GetString("AboutToolStripMenuItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property ADButton1() As String
            Get
                Return ResourceManager.GetString("ADButton1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancella.
        '''</summary>
        Friend Shared ReadOnly Property ADButton2() As String
            Get
                Return ResourceManager.GetString("ADButton2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scarica in seguito.
        '''</summary>
        Friend Shared ReadOnly Property ADchdlnow() As String
            Get
                Return ResourceManager.GetString("ADchdlnow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usa percorso di default.
        '''</summary>
        Friend Shared ReadOnly Property ADchdpath() As String
            Get
                Return ResourceManager.GetString("ADchdpath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usa autorizzazione.
        '''</summary>
        Friend Shared ReadOnly Property ADCheckBox1() As String
            Get
                Return ResourceManager.GetString("ADCheckBox1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remember this path for &lt;Category&gt; category.
        '''</summary>
        Friend Shared ReadOnly Property ADCheckRemember() As String
            Get
                Return ResourceManager.GetString("ADCheckRemember", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aggiungi link.
        '''</summary>
        Friend Shared ReadOnly Property Addlink() As String
            Get
                Return ResourceManager.GetString("Addlink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aggiungi URL.
        '''</summary>
        Friend Shared ReadOnly Property AddLinkToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("AddLinkToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indirizzo :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel1() As String
            Get
                Return ResourceManager.GetString("ADLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nome Utente :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel2() As String
            Get
                Return ResourceManager.GetString("ADLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel3() As String
            Get
                Return ResourceManager.GetString("ADLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descrizione :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel6() As String
            Get
                Return ResourceManager.GetString("ADLabel6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nome file :.
        '''</summary>
        Friend Shared ReadOnly Property ADLabel7() As String
            Get
                Return ResourceManager.GetString("ADLabel7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category.
        '''</summary>
        Friend Shared ReadOnly Property ADlblCategory() As String
            Get
                Return ResourceManager.GetString("ADlblCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descrizione.
        '''</summary>
        Friend Shared ReadOnly Property ADlbldescription() As String
            Get
                Return ResourceManager.GetString("ADlbldescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Organizza i files.
        '''</summary>
        Friend Shared ReadOnly Property ArrangeFilesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ArrangeFilesToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Per Nome File.
        '''</summary>
        Friend Shared ReadOnly Property ByFileNameToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByFileNameToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Per ID.
        '''</summary>
        Friend Shared ReadOnly Property ByIDToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByIDToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Per Data Ultimo Tentativo.
        '''</summary>
        Friend Shared ReadOnly Property ByLastTryDateToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByLastTryDateToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Per Tempo Rimanente.
        '''</summary>
        Friend Shared ReadOnly Property ByLeftTimeToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByLeftTimeToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Per Dimensione.
        '''</summary>
        Friend Shared ReadOnly Property BySizeToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("BySizeToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Per Stato.
        '''</summary>
        Friend Shared ReadOnly Property ByStatusToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByStatusToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Per Velocità.
        '''</summary>
        Friend Shared ReadOnly Property ByToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ByToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usa proxy di sistema.
        '''</summary>
        Friend Shared ReadOnly Property checkuseproxy() As String
            Get
                Return ResourceManager.GetString("checkuseproxy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data ultimo tentativo.
        '''</summary>
        Friend Shared ReadOnly Property CLdate() As String
            Get
                Return ResourceManager.GetString("CLdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descrizione.
        '''</summary>
        Friend Shared ReadOnly Property CLDescription() As String
            Get
                Return ResourceManager.GetString("CLDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Link.
        '''</summary>
        Friend Shared ReadOnly Property CLink() As String
            Get
                Return ResourceManager.GetString("CLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nome.
        '''</summary>
        Friend Shared ReadOnly Property CLname() As String
            Get
                Return ResourceManager.GetString("CLname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property CLnomber() As String
            Get
                Return ResourceManager.GetString("CLnomber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property CLpassword() As String
            Get
                Return ResourceManager.GetString("CLpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dimensione.
        '''</summary>
        Friend Shared ReadOnly Property CLsize() As String
            Get
                Return ResourceManager.GetString("CLsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Velocità.
        '''</summary>
        Friend Shared ReadOnly Property CLspeed() As String
            Get
                Return ResourceManager.GetString("CLspeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stato.
        '''</summary>
        Friend Shared ReadOnly Property CLstatus() As String
            Get
                Return ResourceManager.GetString("CLstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tempo rimanente.
        '''</summary>
        Friend Shared ReadOnly Property CLtime() As String
            Get
                Return ResourceManager.GetString("CLtime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nome utente.
        '''</summary>
        Friend Shared ReadOnly Property CLusername() As String
            Get
                Return ResourceManager.GetString("CLusername", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property DELbtnno() As String
            Get
                Return ResourceManager.GetString("DELbtnno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sì.
        '''</summary>
        Friend Shared ReadOnly Property DELbtnyes() As String
            Get
                Return ResourceManager.GetString("DELbtnyes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non mostrare più questa finestra di dialogo.
        '''</summary>
        Friend Shared ReadOnly Property DELcheckdontshow() As String
            Get
                Return ResourceManager.GetString("DELcheckdontshow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancellazione completata.
        '''</summary>
        Friend Shared ReadOnly Property DeleteAllcompletedToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("DeleteAllcompletedToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sei sicuro di voler cancellare questo/i file?.
        '''</summary>
        Friend Shared ReadOnly Property DELLabel1() As String
            Get
                Return ResourceManager.GetString("DELLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancella richiesta.
        '''</summary>
        Friend Shared ReadOnly Property DELmsgdelete() As String
            Get
                Return ResourceManager.GetString("DELmsgdelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pausa.
        '''</summary>
        Friend Shared ReadOnly Property DLbtnpause() As String
            Get
                Return ResourceManager.GetString("DLbtnpause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Riprendi.
        '''</summary>
        Friend Shared ReadOnly Property DLbtnresume() As String
            Get
                Return ResourceManager.GetString("DLbtnresume", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancella.
        '''</summary>
        Friend Shared ReadOnly Property DLbtnstop() As String
            Get
                Return ResourceManager.GetString("DLbtnstop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;&lt; Nascondi dettagli.
        '''</summary>
        Friend Shared ReadOnly Property DLclosetext() As String
            Get
                Return ResourceManager.GetString("DLclosetext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esci da SD download manager quando è completato.
        '''</summary>
        Friend Shared ReadOnly Property DLexitchek() As String
            Get
                Return ResourceManager.GetString("DLexitchek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forza l&apos;interruzione dei processi.
        '''</summary>
        Friend Shared ReadOnly Property DLforceturnoffcheck() As String
            Get
                Return ResourceManager.GetString("DLforceturnoffcheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scaricati.
        '''</summary>
        Friend Shared ReadOnly Property DLl1() As String
            Get
                Return ResourceManager.GetString("DLl1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stato.
        '''</summary>
        Friend Shared ReadOnly Property DLl2() As String
            Get
                Return ResourceManager.GetString("DLl2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dimensione File.
        '''</summary>
        Friend Shared ReadOnly Property DLl3() As String
            Get
                Return ResourceManager.GetString("DLl3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Velocità.
        '''</summary>
        Friend Shared ReadOnly Property DLl4() As String
            Get
                Return ResourceManager.GetString("DLl4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tempo rimanente.
        '''</summary>
        Friend Shared ReadOnly Property DLl5() As String
            Get
                Return ResourceManager.GetString("DLl5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo di file.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel10() As String
            Get
                Return ResourceManager.GetString("DLLabel10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Possibilità di riprendere.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel14() As String
            Get
                Return ResourceManager.GetString("DLLabel14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tempo trascorso.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel15() As String
            Get
                Return ResourceManager.GetString("DLLabel15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segmenti totali.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel16() As String
            Get
                Return ResourceManager.GetString("DLLabel16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segmento attuale.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel17() As String
            Get
                Return ResourceManager.GetString("DLLabel17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Salva in.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel7() As String
            Get
                Return ResourceManager.GetString("DLLabel7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Queste impostazioni non sono disponibili quando è attiva l&apos;opzione &quot;Mostra la finestra dei download completati&quot;.
        '''</summary>
        Friend Shared ReadOnly Property DLLabel9() As String
            Get
                Return ResourceManager.GetString("DLLabel9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scaricati.
        '''</summary>
        Friend Shared ReadOnly Property DLList1Downloaded() As String
            Get
                Return ResourceManager.GetString("DLList1Downloaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property DLList1ID() As String
            Get
                Return ResourceManager.GetString("DLList1ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stato.
        '''</summary>
        Friend Shared ReadOnly Property DLList1sts() As String
            Get
                Return ResourceManager.GetString("DLList1sts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostra dettagli &gt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property DLopentext() As String
            Get
                Return ResourceManager.GetString("DLopentext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opzione al termine.
        '''</summary>
        Friend Shared ReadOnly Property DLoptiontab() As String
            Get
                Return ResourceManager.GetString("DLoptiontab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spengi il computer quando è completato.
        '''</summary>
        Friend Shared ReadOnly Property DLpcturnoffchek() As String
            Get
                Return ResourceManager.GetString("DLpcturnoffchek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostra la finestra dei download completati.
        '''</summary>
        Friend Shared ReadOnly Property DLshowdialogchk() As String
            Get
                Return ResourceManager.GetString("DLshowdialogchk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stato del download.
        '''</summary>
        Friend Shared ReadOnly Property DLstatustab() As String
            Get
                Return ResourceManager.GetString("DLstatustab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editing Category Properties.
        '''</summary>
        Friend Shared ReadOnly Property EditCat() As String
            Get
                Return ResourceManager.GetString("EditCat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category name.
        '''</summary>
        Friend Shared ReadOnly Property EditCatLabel1() As String
            Get
                Return ResourceManager.GetString("EditCatLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatically put in this category the following file types:.
        '''</summary>
        Friend Shared ReadOnly Property EditCatLabel2() As String
            Get
                Return ResourceManager.GetString("EditCatLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note: type file extensions separated by space(e.g. avi mpg mpeg).
        '''</summary>
        Friend Shared ReadOnly Property EditCatLabel3() As String
            Get
                Return ResourceManager.GetString("EditCatLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save future downloads of this category to the following folder:.
        '''</summary>
        Friend Shared ReadOnly Property EditCatLabel5() As String
            Get
                Return ResourceManager.GetString("EditCatLabel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esci.
        '''</summary>
        Friend Shared ReadOnly Property ExitToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chiudi.
        '''</summary>
        Friend Shared ReadOnly Property FDbtnclose() As String
            Get
                Return ResourceManager.GetString("FDbtnclose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invia.
        '''</summary>
        Friend Shared ReadOnly Property FDbtnersal() As String
            Get
                Return ResourceManager.GetString("FDbtnersal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weblog.
        '''</summary>
        Friend Shared ReadOnly Property FDbtnweb() As String
            Get
                Return ResourceManager.GetString("FDbtnweb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Per favore inserisci il tuo nome e l&apos;indirizzo email.
        '''</summary>
        Friend Shared ReadOnly Property FDGroupBox1() As String
            Get
                Return ResourceManager.GetString("FDGroupBox1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Per favore inviaci dei commenti, suggerimenti o segnala dei bugs nel programma e clicca sul bottone &quot;Invia&quot;.
        '''</summary>
        Friend Shared ReadOnly Property FDGroupBox2() As String
            Get
                Return ResourceManager.GetString("FDGroupBox2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allegare :.
        '''</summary>
        Friend Shared ReadOnly Property FDlblattach() As String
            Get
                Return ResourceManager.GetString("FDlblattach", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E-Mail .
        '''</summary>
        Friend Shared ReadOnly Property FDlblmail() As String
            Get
                Return ResourceManager.GetString("FDlblmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nome.
        '''</summary>
        Friend Shared ReadOnly Property FDlblname() As String
            Get
                Return ResourceManager.GetString("FDlblname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Soggetto.
        '''</summary>
        Friend Shared ReadOnly Property FDlblsubject() As String
            Get
                Return ResourceManager.GetString("FDlblsubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feedback.
        '''</summary>
        Friend Shared ReadOnly Property FeedbackToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("FeedbackToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File.
        '''</summary>
        Friend Shared ReadOnly Property FilesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("FilesToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aiuto.
        '''</summary>
        Friend Shared ReadOnly Property HelpToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("HelpToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Icone.
        '''</summary>
        Friend Shared ReadOnly Property IconsToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("IconsToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feedback.
        '''</summary>
        Friend Shared ReadOnly Property Label10() As String
            Get
                Return ResourceManager.GetString("Label10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Target di rilascio.
        '''</summary>
        Friend Shared ReadOnly Property Label11() As String
            Get
                Return ResourceManager.GetString("Label11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aggiungi link.
        '''</summary>
        Friend Shared ReadOnly Property Label2() As String
            Get
                Return ResourceManager.GetString("Label2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Riprendi.
        '''</summary>
        Friend Shared ReadOnly Property Label3() As String
            Get
                Return ResourceManager.GetString("Label3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interrompi.
        '''</summary>
        Friend Shared ReadOnly Property Label4() As String
            Get
                Return ResourceManager.GetString("Label4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interrompi Tutto.
        '''</summary>
        Friend Shared ReadOnly Property Label5() As String
            Get
                Return ResourceManager.GetString("Label5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scheduler.
        '''</summary>
        Friend Shared ReadOnly Property Label6() As String
            Get
                Return ResourceManager.GetString("Label6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancella.
        '''</summary>
        Friend Shared ReadOnly Property Label7() As String
            Get
                Return ResourceManager.GetString("Label7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancellazione completata.
        '''</summary>
        Friend Shared ReadOnly Property Label8() As String
            Get
                Return ResourceManager.GetString("Label8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opzioni.
        '''</summary>
        Friend Shared ReadOnly Property Label9() As String
            Get
                Return ResourceManager.GetString("Label9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lingua.
        '''</summary>
        Friend Shared ReadOnly Property LanguageToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("LanguageToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Salva in.
        '''</summary>
        Friend Shared ReadOnly Property Llocation() As String
            Get
                Return ResourceManager.GetString("Llocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network is not available , Please check your internet connection and then try again.
        '''</summary>
        Friend Shared ReadOnly Property NoInternet() As String
            Get
                Return ResourceManager.GetString("NoInternet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normale.
        '''</summary>
        Friend Shared ReadOnly Property NormalToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("NormalToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancella.
        '''</summary>
        Friend Shared ReadOnly Property OPbtncancel() As String
            Get
                Return ResourceManager.GetString("OPbtncancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Controlla aggiornamenti.
        '''</summary>
        Friend Shared ReadOnly Property OPbtncheckfornewversion() As String
            Get
                Return ResourceManager.GetString("OPbtncheckfornewversion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modifica.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnedit() As String
            Get
                Return ResourceManager.GetString("OPbtnedit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nuovo.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnnew() As String
            Get
                Return ResourceManager.GetString("OPbtnnew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnok() As String
            Get
                Return ResourceManager.GetString("OPbtnok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rimuovi.
        '''</summary>
        Friend Shared ReadOnly Property OPbtnremove() As String
            Get
                Return ResourceManager.GetString("OPbtnremove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aggiungi.
        '''</summary>
        Friend Shared ReadOnly Property opButton1() As String
            Get
                Return ResourceManager.GetString("opButton1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default.
        '''</summary>
        Friend Shared ReadOnly Property opButton2() As String
            Get
                Return ResourceManager.GetString("opButton2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rimuovi.
        '''</summary>
        Friend Shared ReadOnly Property opButton3() As String
            Get
                Return ResourceManager.GetString("opButton3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleziona font.
        '''</summary>
        Friend Shared ReadOnly Property OPButton4() As String
            Get
                Return ResourceManager.GetString("OPButton4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleziona i colori del testo.
        '''</summary>
        Friend Shared ReadOnly Property OPButton5() As String
            Get
                Return ResourceManager.GetString("OPButton5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleziona il colore di background.
        '''</summary>
        Friend Shared ReadOnly Property OPButton6() As String
            Get
                Return ResourceManager.GetString("OPButton6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ripristino di default.
        '''</summary>
        Friend Shared ReadOnly Property OPButton7() As String
            Get
                Return ResourceManager.GetString("OPButton7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Controlla automaticamente gli aggiornamenti.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckautoupdate() As String
            Get
                Return ResourceManager.GetString("OPcheckautoupdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download non riuscito.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckcancelled() As String
            Get
                Return ResourceManager.GetString("OPcheckcancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download completato.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckcompleted() As String
            Get
                Return ResourceManager.GetString("OPcheckcompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usa percorso di default per i downloads.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckdefaultpath() As String
            Get
                Return ResourceManager.GetString("OPcheckdefaultpath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non mostrare la finestra di eliminazione quando si cancellano files dalla lista.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckdontshoedelete() As String
            Get
                Return ResourceManager.GetString("OPcheckdontshoedelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prendi il link del download dagli appunti.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckgrabfromclipboard() As String
            Get
                Return ResourceManager.GetString("OPcheckgrabfromclipboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilizzare vecchie icone.
        '''</summary>
        Friend Shared ReadOnly Property OPCheckOldIcons() As String
            Get
                Return ResourceManager.GetString("OPCheckOldIcons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostra una notifica sul desktop quando il download è Completato.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckshownotification() As String
            Get
                Return ResourceManager.GetString("OPcheckshownotification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Avvia SD Download Manager all&apos;avvio di windows.
        '''</summary>
        Friend Shared ReadOnly Property OPcheckstartup() As String
            Get
                Return ResourceManager.GetString("OPcheckstartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Avvia automaticamente il download solo per questo tipo di file.
        '''</summary>
        Friend Shared ReadOnly Property opcheckusefiletype() As String
            Get
                Return ResourceManager.GetString("opcheckusefiletype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property OPCpass() As String
            Get
                Return ResourceManager.GetString("OPCpass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sito/Percorso.
        '''</summary>
        Friend Shared ReadOnly Property OPCsite() As String
            Get
                Return ResourceManager.GetString("OPCsite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utente.
        '''</summary>
        Friend Shared ReadOnly Property OPCuser() As String
            Get
                Return ResourceManager.GetString("OPCuser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apri con.
        '''</summary>
        Friend Shared ReadOnly Property OPEbtnopenwith() As String
            Get
                Return ResourceManager.GetString("OPEbtnopenwith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apri.
        '''</summary>
        Friend Shared ReadOnly Property OPEButton1() As String
            Get
                Return ResourceManager.GetString("OPEButton1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apri cartella.
        '''</summary>
        Friend Shared ReadOnly Property OPEButton3() As String
            Get
                Return ResourceManager.GetString("OPEButton3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chiudi.
        '''</summary>
        Friend Shared ReadOnly Property OPEButton4() As String
            Get
                Return ResourceManager.GetString("OPEButton4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download completato.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel1() As String
            Get
                Return ResourceManager.GetString("OPELabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indirizzo.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel2() As String
            Get
                Return ResourceManager.GetString("OPELabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il file salvato come.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel3() As String
            Get
                Return ResourceManager.GetString("OPELabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scaricati.
        '''</summary>
        Friend Shared ReadOnly Property OPELabel5() As String
            Get
                Return ResourceManager.GetString("OPELabel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apri cartella.
        '''</summary>
        Friend Shared ReadOnly Property OpenFolderToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenFolderToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apri app.
        '''</summary>
        Friend Shared ReadOnly Property OpenSDMToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenSDMToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apri.
        '''</summary>
        Friend Shared ReadOnly Property OpenToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apri con....
        '''</summary>
        Friend Shared ReadOnly Property OpenWithToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OpenWithToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opzione.
        '''</summary>
        Friend Shared ReadOnly Property OPfrmoption() As String
            Get
                Return ResourceManager.GetString("OPfrmoption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impostazioni Generali.
        '''</summary>
        Friend Shared ReadOnly Property OPGroupBox1() As String
            Get
                Return ResourceManager.GetString("OPGroupBox1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleziona suoni ed eventi.
        '''</summary>
        Friend Shared ReadOnly Property OPGroupBox2() As String
            Get
                Return ResourceManager.GetString("OPGroupBox2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleziona font e altre impostazioni dell&apos;Interfaccia Utente.
        '''</summary>
        Friend Shared ReadOnly Property OPGroupBox4() As String
            Get
                Return ResourceManager.GetString("OPGroupBox4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impostazione Generale.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel1() As String
            Get
                Return ResourceManager.GetString("OPLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impostazione dell&apos;interfaccia utente.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel11() As String
            Get
                Return ResourceManager.GetString("OPLabel11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se cambi il numero delle connessioni tutti i downloads ricominceranno dall&apos;inizio.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel12() As String
            Get
                Return ResourceManager.GetString("OPLabel12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resetta automaticamente la durata del download.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel13() As String
            Get
                Return ResourceManager.GetString("OPLabel13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secondo.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel14() As String
            Get
                Return ResourceManager.GetString("OPLabel14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cache Dimensione.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel15() As String
            Get
                Return ResourceManager.GetString("OPLabel15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impostazioni Audio.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel3() As String
            Get
                Return ResourceManager.GetString("OPLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nomi utente e passwords per server/siti.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel5() As String
            Get
                Return ResourceManager.GetString("OPLabel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipi di file scaricati.
        '''</summary>
        Friend Shared ReadOnly Property opLabel8() As String
            Get
                Return ResourceManager.GetString("opLabel8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numero di connessioni.
        '''</summary>
        Friend Shared ReadOnly Property OPLabel9() As String
            Get
                Return ResourceManager.GetString("OPLabel9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verifica in corso, Per favore aspetta ....
        '''</summary>
        Friend Shared ReadOnly Property OPlblcheck() As String
            Get
                Return ResourceManager.GetString("OPlblcheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Audio.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage1() As String
            Get
                Return ResourceManager.GetString("OPTabPage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generale.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage2() As String
            Get
                Return ResourceManager.GetString("OPTabPage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login siti.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage3() As String
            Get
                Return ResourceManager.GetString("OPTabPage3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipi di file.
        '''</summary>
        Friend Shared ReadOnly Property opTabPage4() As String
            Get
                Return ResourceManager.GetString("opTabPage4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interfaccia utente.
        '''</summary>
        Friend Shared ReadOnly Property OPTabPage5() As String
            Get
                Return ResourceManager.GetString("OPTabPage5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opzioni.
        '''</summary>
        Friend Shared ReadOnly Property OptionToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("OptionToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chiudi.
        '''</summary>
        Friend Shared ReadOnly Property PRbtnclose() As String
            Get
                Return ResourceManager.GetString("PRbtnclose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apri.
        '''</summary>
        Friend Shared ReadOnly Property PRbtnopen() As String
            Get
                Return ResourceManager.GetString("PRbtnopen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apri.
        '''</summary>
        Friend Shared ReadOnly Property PRbtnopenlink() As String
            Get
                Return ResourceManager.GetString("PRbtnopenlink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proprietà File.
        '''</summary>
        Friend Shared ReadOnly Property PRfrmpropertise() As String
            Get
                Return ResourceManager.GetString("PRfrmpropertise", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel1() As String
            Get
                Return ResourceManager.GetString("PRLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Risultato :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel10() As String
            Get
                Return ResourceManager.GetString("PRLabel10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Referer :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel14() As String
            Get
                Return ResourceManager.GetString("PRLabel14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stato :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel2() As String
            Get
                Return ResourceManager.GetString("PRLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dimensione :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel3() As String
            Get
                Return ResourceManager.GetString("PRLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Salva in :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel4() As String
            Get
                Return ResourceManager.GetString("PRLabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indirizzo :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel5() As String
            Get
                Return ResourceManager.GetString("PRLabel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descrizione :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel6() As String
            Get
                Return ResourceManager.GetString("PRLabel6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entra :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel7() As String
            Get
                Return ResourceManager.GetString("PRLabel7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel8() As String
            Get
                Return ResourceManager.GetString("PRLabel8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data ultimo tentativo :.
        '''</summary>
        Friend Shared ReadOnly Property PRLabel9() As String
            Get
                Return ResourceManager.GetString("PRLabel9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proprietà.
        '''</summary>
        Friend Shared ReadOnly Property PropertiseToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("PropertiseToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scarica nuovamente.
        '''</summary>
        Friend Shared ReadOnly Property RedownloadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("RedownloadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancella.
        '''</summary>
        Friend Shared ReadOnly Property RemoveToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("RemoveToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Riprendi download.
        '''</summary>
        Friend Shared ReadOnly Property ResumeDownloadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ResumeDownloadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Applica.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnapply() As String
            Get
                Return ResourceManager.GetString("SCbtnapply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nascondi.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnclose() As String
            Get
                Return ResourceManager.GetString("SCbtnclose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chiudi.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnexit() As String
            Get
                Return ResourceManager.GetString("SCbtnexit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inizia ora.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnstart() As String
            Get
                Return ResourceManager.GetString("SCbtnstart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ferma.
        '''</summary>
        Friend Shared ReadOnly Property SCbtnstop() As String
            Get
                Return ResourceManager.GetString("SCbtnstop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descrizione.
        '''</summary>
        Friend Shared ReadOnly Property SCCdescriptionl() As String
            Get
                Return ResourceManager.GetString("SCCdescriptionl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esci da SD Download Manager quando è completato.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckexit() As String
            Get
                Return ResourceManager.GetString("SCcheckexit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Venerdì.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckfriday() As String
            Get
                Return ResourceManager.GetString("SCcheckfriday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resetta il modem quando è completato.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckhangmodem() As String
            Get
                Return ResourceManager.GetString("SCcheckhangmodem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lunedì.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckmonday() As String
            Get
                Return ResourceManager.GetString("SCcheckmonday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apri il seguente file quando è pronto.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckopenfile() As String
            Get
                Return ResourceManager.GetString("SCcheckopenfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numero di tentativi per ogni file se il download non riesce :.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckretrycount() As String
            Get
                Return ResourceManager.GetString("SCcheckretrycount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sabato.
        '''</summary>
        Friend Shared ReadOnly Property SCchecksaturday() As String
            Get
                Return ResourceManager.GetString("SCchecksaturday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Avvia il download a.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckstarttime() As String
            Get
                Return ResourceManager.GetString("SCcheckstarttime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inizia il download all&apos;avvio di SD Download Manager.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckstartup() As String
            Get
                Return ResourceManager.GetString("SCcheckstartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ferma il download a.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckstoptime() As String
            Get
                Return ResourceManager.GetString("SCcheckstoptime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Domenica.
        '''</summary>
        Friend Shared ReadOnly Property SCchecksunday() As String
            Get
                Return ResourceManager.GetString("SCchecksunday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giovedì.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckthursday() As String
            Get
                Return ResourceManager.GetString("SCcheckthursday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Martedì.
        '''</summary>
        Friend Shared ReadOnly Property SCchecktuesday() As String
            Get
                Return ResourceManager.GetString("SCchecktuesday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spengi il computer quando è completato.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckturnoff() As String
            Get
                Return ResourceManager.GetString("SCcheckturnoff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mercoledì.
        '''</summary>
        Friend Shared ReadOnly Property SCcheckwednesday() As String
            Get
                Return ResourceManager.GetString("SCcheckwednesday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property SCCidl() As String
            Get
                Return ResourceManager.GetString("SCCidl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data ultimo tentativo.
        '''</summary>
        Friend Shared ReadOnly Property SCClasttryl() As String
            Get
                Return ResourceManager.GetString("SCClasttryl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tempo rimanente.
        '''</summary>
        Friend Shared ReadOnly Property SCClefttimel() As String
            Get
                Return ResourceManager.GetString("SCClefttimel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Link.
        '''</summary>
        Friend Shared ReadOnly Property SCClinkl() As String
            Get
                Return ResourceManager.GetString("SCClinkl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nome.
        '''</summary>
        Friend Shared ReadOnly Property SCCNamel() As String
            Get
                Return ResourceManager.GetString("SCCNamel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property SCCpasswordl() As String
            Get
                Return ResourceManager.GetString("SCCpasswordl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Salva in.
        '''</summary>
        Friend Shared ReadOnly Property SCCsavetol() As String
            Get
                Return ResourceManager.GetString("SCCsavetol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dimensione.
        '''</summary>
        Friend Shared ReadOnly Property SCCsizel() As String
            Get
                Return ResourceManager.GetString("SCCsizel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Velocità.
        '''</summary>
        Friend Shared ReadOnly Property SCCSpeedl() As String
            Get
                Return ResourceManager.GetString("SCCSpeedl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stato.
        '''</summary>
        Friend Shared ReadOnly Property SCCstatusl() As String
            Get
                Return ResourceManager.GetString("SCCstatusl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nome utente.
        '''</summary>
        Friend Shared ReadOnly Property SCCusernamel() As String
            Get
                Return ResourceManager.GetString("SCCusernamel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scaricati :.
        '''</summary>
        Friend Shared ReadOnly Property SCdledlbl() As String
            Get
                Return ResourceManager.GetString("SCdledlbl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forza l&apos;interruzione dei processi.
        '''</summary>
        Friend Shared ReadOnly Property SCforceturnoffcheck() As String
            Get
                Return ResourceManager.GetString("SCforceturnoffcheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scheduler.
        '''</summary>
        Friend Shared ReadOnly Property SCfrmschedule() As String
            Get
                Return ResourceManager.GetString("SCfrmschedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pianifica.
        '''</summary>
        Friend Shared ReadOnly Property ScheduleToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ScheduleToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download.
        '''</summary>
        Friend Shared ReadOnly Property SCLabel3() As String
            Get
                Return ResourceManager.GetString("SCLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to file allo stesso tempo.
        '''</summary>
        Friend Shared ReadOnly Property SCLabel4() As String
            Get
                Return ResourceManager.GetString("SCLabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giornaliero.
        '''</summary>
        Friend Shared ReadOnly Property SCrbdayli() As String
            Get
                Return ResourceManager.GetString("SCrbdayli", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Una volta al.
        '''</summary>
        Friend Shared ReadOnly Property SCrbonce() As String
            Get
                Return ResourceManager.GetString("SCrbonce", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rimanenti :.
        '''</summary>
        Friend Shared ReadOnly Property SCremainlbl() As String
            Get
                Return ResourceManager.GetString("SCremainlbl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pianifica.
        '''</summary>
        Friend Shared ReadOnly Property SCTabPage1() As String
            Get
                Return ResourceManager.GetString("SCTabPage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Files in coda.
        '''</summary>
        Friend Shared ReadOnly Property SCTabPage2() As String
            Get
                Return ResourceManager.GetString("SCTabPage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostra target di rilascio.
        '''</summary>
        Friend Shared ReadOnly Property ShowDropTargetToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ShowDropTargetToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Piccolo.
        '''</summary>
        Friend Shared ReadOnly Property SmallToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("SmallToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ferma download.
        '''</summary>
        Friend Shared ReadOnly Property StopDownloadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("StopDownloadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annullato.
        '''</summary>
        Friend Shared ReadOnly Property stsCanceled() As String
            Get
                Return ResourceManager.GetString("stsCanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to cancellatura .
        '''</summary>
        Friend Shared ReadOnly Property stsCanceling() As String
            Get
                Return ResourceManager.GetString("stsCanceling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completato.
        '''</summary>
        Friend Shared ReadOnly Property stsCompleted() As String
            Get
                Return ResourceManager.GetString("stsCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Collegamento ....
        '''</summary>
        Friend Shared ReadOnly Property stsConnecting() As String
            Get
                Return ResourceManager.GetString("stsConnecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download non riuscito.
        '''</summary>
        Friend Shared ReadOnly Property stsDLfaild() As String
            Get
                Return ResourceManager.GetString("stsDLfaild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download non riuscito - Cercando di nuovo per scaricare.
        '''</summary>
        Friend Shared ReadOnly Property stsDLfaild_Tryingagain() As String
            Get
                Return ResourceManager.GetString("stsDLfaild_Tryingagain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scarica resettato.
        '''</summary>
        Friend Shared ReadOnly Property stsDLresetted() As String
            Get
                Return ResourceManager.GetString("stsDLresetted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ripristino scaricare.
        '''</summary>
        Friend Shared ReadOnly Property stsDLresetting() As String
            Get
                Return ResourceManager.GetString("stsDLresetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scaricare.
        '''</summary>
        Friend Shared ReadOnly Property stsDownloading() As String
            Get
                Return ResourceManager.GetString("stsDownloading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to non riuscito.
        '''</summary>
        Friend Shared ReadOnly Property stsfaild() As String
            Get
                Return ResourceManager.GetString("stsfaild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File successo scaricato e fusa.
        '''</summary>
        Friend Shared ReadOnly Property stsMerged() As String
            Get
                Return ResourceManager.GetString("stsMerged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unire le parti scaricate - attendere prego ....
        '''</summary>
        Friend Shared ReadOnly Property stsMergin() As String
            Get
                Return ResourceManager.GetString("stsMergin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In pausa.
        '''</summary>
        Friend Shared ReadOnly Property stsPaused() As String
            Get
                Return ResourceManager.GetString("stsPaused", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mettere in pausa.
        '''</summary>
        Friend Shared ReadOnly Property stsPausing() As String
            Get
                Return ResourceManager.GetString("stsPausing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to scaricare partire.
        '''</summary>
        Friend Shared ReadOnly Property stsStarting() As String
            Get
                Return ResourceManager.GetString("stsStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloads.
        '''</summary>
        Friend Shared ReadOnly Property TabPage1() As String
            Get
                Return ResourceManager.GetString("TabPage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logs.
        '''</summary>
        Friend Shared ReadOnly Property TabPage2() As String
            Get
                Return ResourceManager.GetString("TabPage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scarica nuovamente.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem10() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tutto in Pausa.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem12() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interrompi Tutto.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem13() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compito.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem3() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem4() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aggiungi nuovo link.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem5() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esci.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem6() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ferma download.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem7() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rimuovi.
        '''</summary>
        Friend Shared ReadOnly Property ToolStripMenuItem8() As String
            Get
                Return ResourceManager.GetString("ToolStripMenuItem8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancella.
        '''</summary>
        Friend Shared ReadOnly Property UPbtncancel() As String
            Get
                Return ResourceManager.GetString("UPbtncancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property UPbtnok() As String
            Get
                Return ResourceManager.GetString("UPbtnok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entra nel sito.
        '''</summary>
        Friend Shared ReadOnly Property UPEfrmuserpass() As String
            Get
                Return ResourceManager.GetString("UPEfrmuserpass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server/Percorso.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel1() As String
            Get
                Return ResourceManager.GetString("UPELabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nota : Digita il percorso solo se hai nomi differenti di login per diverse directory di server.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel2() As String
            Get
                Return ResourceManager.GetString("UPELabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nome utente.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel3() As String
            Get
                Return ResourceManager.GetString("UPELabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property UPELabel4() As String
            Get
                Return ResourceManager.GetString("UPELabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entra nel sito.
        '''</summary>
        Friend Shared ReadOnly Property UPfrmuserpass() As String
            Get
                Return ResourceManager.GetString("UPfrmuserpass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server/Percorso.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel1() As String
            Get
                Return ResourceManager.GetString("UPLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nota : Digita il percorso solo se hai nomi differenti di login per diverse directory di server.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel2() As String
            Get
                Return ResourceManager.GetString("UPLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nome utente.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel3() As String
            Get
                Return ResourceManager.GetString("UPLabel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property UPLabel4() As String
            Get
                Return ResourceManager.GetString("UPLabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Visualizza.
        '''</summary>
        Friend Shared ReadOnly Property ViewToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ViewToolStripMenuItem", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
